# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('units_returned', models.IntegerField(default=0)),
                ('units_written_off', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_product_performance',
            },
        ),
        migrations.CreateModel(
            name='AgingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_type', models.CharField(choices=[('customer', 'Клиент (A/R)'), ('supplier', 'Поставщик (A/P)')], max_length=10)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('bucket_0_30', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bucket_31_60', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bucket_61_90', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('bucket_90_plus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'analytics_aging_report',
            },
        ),
    ]
