# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productperformance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productperformance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterUniqueTogether(
            name='agingreport',
            unique_together={('tenant', 'report_type', 'entity_id')},
        ),
        migrations.AlterUniqueTogether(
            name='productperformance',
            unique_together={('product', 'period_start', 'period_end')},
        ),
    ]
