# Generated by Django 5.1.15 on 2026-04-18 00:32

import apps.core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('receipt_type', models.CharField(choices=[('BUSINESS_OWNED', 'Собственный'), ('MUDARABA', 'Мудараба'), ('MUSHARAKA', 'Мушарака'), ('SUPPLIER_PURCHASE', 'Закупка у поставщика'), ('CONSIGNMENT', 'Консигнация')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён')], default='draft', max_length=20)),
                ('date', models.DateTimeField()),
                ('payable_terms', models.JSONField(blank=True, help_text='For SUPPLIER_PURCHASE: {type: paid|credit, due_date: date}', null=True)),
                ('consignment_rule', models.JSONField(blank=True, help_text='For CONSIGNMENT: {type: margin|commission, value: decimal}', null=True)),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'inventory_receipt',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'db_table': 'inventory_receipt_line',
            },
        ),
        migrations.CreateModel(
            name='ReceiptParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('participant_type', models.CharField(choices=[('business', 'Бизнес'), ('investor', 'Инвестор')], max_length=20)),
                ('entity_id', models.IntegerField(help_text='ID of Investor or Business.')),
                ('capital_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('capital_ratio', models.DecimalField(decimal_places=4, help_text='Auto-calculated: capital_amount / total_capital.', max_digits=5)),
                ('profit_ratio', models.DecimalField(decimal_places=4, help_text='Agreed profit share (0..1). Sum of all must = 1.0.', max_digits=5)),
            ],
            options={
                'db_table': 'inventory_receipt_participant',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('sale', 'Продажа'), ('transfer', 'Перемещение'), ('return', 'Возврат'), ('writeoff', 'Списание'), ('adjustment', 'Корректировка')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive = in, Negative = out.')),
                ('reference_type', models.CharField(blank=True, default='', help_text='E.g., sale, receipt, risk_event.', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the related object.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('STORAGE', 'Склад'), ('SHOP', 'Магазин')], default='SHOP', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_warehouse',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity_initial', models.PositiveIntegerField()),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, help_text='Supplier price at receipt time — no landed costs allocated.', max_digits=14)),
                ('landed_cost_per_unit', models.DecimalField(decimal_places=2, help_text='Unit purchase price + allocated landed expenses. Immutable.', max_digits=14)),
                ('contract_snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of partner shares at receive time. Shape: {mudaraba_ratio, loss_rule, partners: [{partner_id, role, capital_share, profit_share}]}')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False when total quantity_remaining across warehouses == 0.')),
                ('procurement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='partnerships.procurementitem')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.productvariant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'inventory_lot',
            },
        ),
        migrations.CreateModel(
            name='LotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.lot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'inventory_lot_stock',
            },
        ),
    ]
