# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('investors', '0001_initial'),
        ('partnerships', '0001_initial'),
        ('risk', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='procurement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='partnerships.procurementitem'),
        ),
        migrations.AddField(
            model_name='lot',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='investor_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='investors.investorcontract'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='lot',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='lot',
            name='receipt_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot', to='inventory.receiptline'),
        ),
        migrations.AddField(
            model_name='receiptparticipant',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='inventory.receipt'),
        ),
        migrations.AddField(
            model_name='receiptparticipant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='return_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals', to='sales.return'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='risk_event_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals', to='risk.riskevent'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='lotstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_stocks', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['product_variant', 'is_active'], name='inventory_l_product_e49943_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['receipt'], name='inventory_l_receipt_f5ca08_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['procurement_item'], name='inventory_l_procure_97f48d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', 'movement_type'], name='inventory_s_lot_id_9380e1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'created_at'], name='inventory_s_tenant__8f97f0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdisposal',
            index=models.Index(fields=['lot', 'reason'], name='inventory_s_lot_id_8b24f3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdisposal',
            index=models.Index(fields=['tenant', 'created_at'], name='inventory_s_tenant__b2cb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'receipt_type', 'status'], name='inventory_r_tenant__904eb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_receipt_idempotent'),
        ),
        migrations.AddIndex(
            model_name='lotstock',
            index=models.Index(fields=['warehouse', 'quantity_remaining'], name='inventory_l_warehou_fe7645_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotstock',
            constraint=models.UniqueConstraint(fields=('lot', 'warehouse'), name='uq_lotstock_lot_warehouse'),
        ),
    ]
