# Generated by Django 5.1.15 on 2026-04-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_receipt_functional_amount_uzs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='receipt_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot', to='inventory.receiptline'),
        ),
    ]
