# Generated by Django 5.1.15 on 2026-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_lot_received_at_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_owned',
            field=models.BooleanField(default=True, help_text='E09: False for CONSIGNED lots — goods belong to supplier until sold.'),
        ),
    ]
