# Generated by Django 5.1.15 on 2026-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_lot_is_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='reversed',
            field=models.BooleanField(default=False, help_text='E09 Slice 6: True when the receive batch that created this lot was reversed. Excluded from FIFO.'),
        ),
    ]
