# Generated by Django 5.1.15 on 2026-05-25 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesposRawEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('slug', models.CharField(max_length=64)),
                ('body', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('source_request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yespos_raw_events', to='core.business')),
            ],
            options={
                'db_table': 'integrations_yespos_raw_event',
                'indexes': [models.Index(fields=['received_at'], name='integration_receive_1df262_idx'), models.Index(fields=['slug', 'received_at'], name='integration_slug_dc0fdd_idx'), models.Index(fields=['tenant', 'received_at'], name='integration_tenant__4ba118_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_request_id__isnull', False)), fields=('tenant', 'source_request_id'), name='uq_yespos_event_request_id')],
            },
        ),
    ]
