# Generated by Django 5.1.15 on 2026-05-13 00:47

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'businesses',
                'db_table': 'core_business',
            },
        ),
        migrations.CreateModel(
            name='BusinessInvestorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACTIVE', 'Активен'), ('REVOKED', 'Отозван'), ('BLOCKED', 'Заблокирован')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Вручную'), ('INVITE', 'Инвайт')], default='MANUAL', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_investor_relations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_business_investor_relation',
            },
        ),
        migrations.CreateModel(
            name='ExcelImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_kind', models.CharField(default='json', max_length=50)),
                ('source_ref', models.CharField(blank=True, default='', max_length=500)),
                ('mode', models.CharField(choices=[('dry-run', 'Dry run'), ('load-master', 'Load master'), ('load-transactions', 'Load transactions'), ('reconcile', 'Reconcile')], max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_excel_import_batch',
            },
        ),
        migrations.CreateModel(
            name='ExcelImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_sheet', models.CharField(db_index=True, max_length=100)),
                ('source_row_id', models.CharField(max_length=64)),
                ('row_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(blank=True, null=True)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('failure_category', models.CharField(blank=True, choices=[('parse', 'Parse'), ('mapping', 'Mapping'), ('domain', 'Domain'), ('other', 'Other')], default='', max_length=20)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('parsed', 'Parsed'), ('applied', 'Applied'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='staged', max_length=20)),
                ('target_model', models.CharField(blank=True, default='', max_length=120)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Functional amount in UZS.', max_digits=16, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.excelimportbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_excel_import_row',
            },
        ),
        migrations.CreateModel(
            name='InvestorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(db_index=True, default=apps.core.models.generate_invite_token, max_length=96, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принят'), ('REVOKED', 'Отозван'), ('EXPIRED', 'Истёк')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_investor_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_investor_invites', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='core.businessinvestorrelation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_investor_invite',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('tenant_id', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'core_outbox_event',
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['processed_at', 'tenant_id'], name='idx_outbox_unprocessed')],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_partner',
            },
        ),
        migrations.AddField(
            model_name='businessinvestorrelation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations', to='core.partner'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbekcha"), ('en', 'English')], default='ru', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='micropos_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_preference',
            },
        ),
        migrations.CreateModel(
            name='BusinessRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('business_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Подтверждена'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='core.business')),
                ('approved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_business_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_business_registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_business_registration_request',
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_busine_status_7986eb_idx'), models.Index(fields=['username', 'status'], name='core_busine_usernam_630e4b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='excelimportbatch',
            index=models.Index(fields=['tenant', 'mode', 'status'], name='core_excel__tenant__dc35ee_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportbatch',
            index=models.Index(fields=['tenant', 'created_at'], name='core_excel__tenant__1f5e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportrow',
            index=models.Index(fields=['tenant', 'source_sheet', 'row_fingerprint'], name='core_excel__tenant__5603dc_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportrow',
            index=models.Index(fields=['batch', 'status'], name='core_excel__batch_i_6338d9_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportrow',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='core_excel__tenant__50829c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='excelimportrow',
            unique_together={('batch', 'source_sheet', 'source_row_id')},
        ),
        migrations.AddIndex(
            model_name='investorinvite',
            index=models.Index(fields=['tenant', 'status'], name='core_invest_tenant__be25c0_idx'),
        ),
        migrations.AddIndex(
            model_name='investorinvite',
            index=models.Index(fields=['expires_at'], name='core_invest_expires_77dcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='core_partne_tenant__5bfe67_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvestorrelation',
            index=models.Index(fields=['tenant', 'status'], name='core_busine_tenant__77b141_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvestorrelation',
            index=models.Index(fields=['partner', 'status'], name='core_busine_partner_053bdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessinvestorrelation',
            constraint=models.UniqueConstraint(fields=('tenant', 'partner'), name='uq_business_investor_relation'),
        ),
    ]
