# Generated by Django 5.1.15 on 2026-04-16 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_kind', models.CharField(default='json', max_length=50)),
                ('source_ref', models.CharField(blank=True, default='', max_length=500)),
                ('mode', models.CharField(choices=[('dry-run', 'Dry run'), ('load-master', 'Load master'), ('load-transactions', 'Load transactions'), ('reconcile', 'Reconcile')], max_length=40)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_excelimportbatch_set', to='core.business')),
            ],
            options={
                'db_table': 'core_excel_import_batch',
                'indexes': [models.Index(fields=['tenant', 'mode', 'status'], name='core_excel_i_tenant__f39388_idx'), models.Index(fields=['tenant', 'created_at'], name='core_excel_i_tenant__5e2982_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_sheet', models.CharField(db_index=True, max_length=100)),
                ('source_row_id', models.CharField(max_length=64)),
                ('row_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(blank=True, null=True)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('parsed', 'Parsed'), ('applied', 'Applied'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='staged', max_length=20)),
                ('target_model', models.CharField(blank=True, default='', max_length=120)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Functional amount in UZS.', max_digits=16, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.excelimportbatch')),
                ('tenant', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_excelimportrow_set', to='core.business')),
            ],
            options={
                'db_table': 'core_excel_import_row',
                'indexes': [models.Index(fields=['tenant', 'source_sheet', 'row_fingerprint'], name='core_excel_i_tenant__d9e9df_idx'), models.Index(fields=['batch', 'status'], name='core_excel_i_batch_i_d0c194_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='core_excel_i_tenant__2f6f85_idx')],
                'unique_together': {('batch', 'source_sheet', 'source_row_id')},
            },
        ),
    ]
