# Generated by Django 5.1.15 on 2026-07-04 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('public_slug', models.SlugField(blank=True, max_length=96, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_investment_profile',
                'indexes': [models.Index(fields=['is_active', 'display_name'], name='core_invest_is_acti_6ebcca_idx')],
            },
        ),
    ]
