# Generated by Codex on 2026-04-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import apps.core.models


def create_existing_investor_relations(apps, schema_editor):
    Partner = apps.get_model('core', 'Partner')
    BusinessInvestorRelation = apps.get_model('core', 'BusinessInvestorRelation')

    for partner in Partner.objects.filter(
        role='INVESTOR',
        is_active=True,
        deleted_at__isnull=True,
    ):
        BusinessInvestorRelation.objects.get_or_create(
            tenant_id=partner.tenant_id,
            partner_id=partner.id,
            defaults={
                'status': 'ACTIVE',
                'source': 'MANUAL',
                'created_by_id': None,
                'notes': 'Backfilled for existing investor partner.',
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outboxevent_failure_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInvestorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACTIVE', 'Активен'), ('REVOKED', 'Отозван'), ('BLOCKED', 'Заблокирован')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Вручную'), ('INVITE', 'Инвайт')], default='MANUAL', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_investor_relations', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_relations', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_business_investor_relation',
            },
        ),
        migrations.CreateModel(
            name='InvestorInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('token', models.CharField(db_index=True, default=apps.core.models.generate_invite_token, max_length=96, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принят'), ('REVOKED', 'Отозван'), ('EXPIRED', 'Истёк')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_investor_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_investor_invites', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='core.businessinvestorrelation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'core_investor_invite',
            },
        ),
        migrations.AddConstraint(
            model_name='businessinvestorrelation',
            constraint=models.UniqueConstraint(fields=('tenant', 'partner'), name='uq_business_investor_relation'),
        ),
        migrations.AddIndex(
            model_name='businessinvestorrelation',
            index=models.Index(fields=['tenant', 'status'], name='core_busine_tenant__77b141_idx'),
        ),
        migrations.AddIndex(
            model_name='businessinvestorrelation',
            index=models.Index(fields=['partner', 'status'], name='core_busine_partner_053bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='investorinvite',
            index=models.Index(fields=['tenant', 'status'], name='core_invest_tenant__be25c0_idx'),
        ),
        migrations.AddIndex(
            model_name='investorinvite',
            index=models.Index(fields=['expires_at'], name='core_invest_expires_77dcd2_idx'),
        ),
        migrations.RunPython(create_existing_investor_relations, noop_reverse),
    ]
