# Generated by Django 5.1.15 on 2026-04-15 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_excelimportbatch_excelimportrow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='excelimportbatch',
            new_name='core_excel__tenant__dc35ee_idx',
            old_name='core_excel_i_tenant__f39388_idx',
        ),
        migrations.RenameIndex(
            model_name='excelimportbatch',
            new_name='core_excel__tenant__1f5e0d_idx',
            old_name='core_excel_i_tenant__5e2982_idx',
        ),
        migrations.RenameIndex(
            model_name='excelimportrow',
            new_name='core_excel__tenant__5603dc_idx',
            old_name='core_excel_i_tenant__d9e9df_idx',
        ),
        migrations.RenameIndex(
            model_name='excelimportrow',
            new_name='core_excel__batch_i_6338d9_idx',
            old_name='core_excel_i_batch_i_d0c194_idx',
        ),
        migrations.RenameIndex(
            model_name='excelimportrow',
            new_name='core_excel__tenant__50829c_idx',
            old_name='core_excel_i_tenant__2f6f85_idx',
        ),
        migrations.AddField(
            model_name='excelimportrow',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('parse', 'Parse'), ('mapping', 'Mapping'), ('domain', 'Domain'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='excelimportbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='excelimportrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
    ]
