# Generated by Django 5.1.15 on 2026-04-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investor_invites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('business_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Подтверждена'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_requests', to='core.business')),
                ('approved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_business_registration_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_business_registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_business_registration_request',
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_busine_status_7986eb_idx'), models.Index(fields=['username', 'status'], name='core_busine_usernam_630e4b_idx')],
            },
        ),
    ]
