server {
    listen 80;
    server_name _;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location /static/ {
        alias /var/www/static/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /var/www/media/;
        access_log off;
        expires 7d;
    }

    location / {
        return 404;
    }
}
