# Generated by Django 5.1.15 on 2026-04-18 09:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'risk_inventory_check',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expected_quantity', models.PositiveIntegerField()),
                ('actual_quantity', models.PositiveIntegerField()),
                ('difference', models.IntegerField(help_text='actual - expected. Negative = shortage.')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='risk.inventorycheck')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'risk_inventory_check_line',
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('writeoff', 'Списание'), ('damage', 'Брак'), ('loss', 'Пропажа'), ('return', 'Возврат'), ('stock_mismatch', 'Расхождение при инвентаризации'), ('adjustment', 'Корректировка'), ('cash_mismatch', 'Расхождение кассы')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('monetary_impact', models.DecimalField(decimal_places=2, default=0, help_text='Financial impact (cost of lost goods, cash difference, etc.).', max_digits=14)),
                ('affects_investor', models.BooleanField(default=False, help_text='Auto-set: True if lot belongs to MUDARABA/MUSHARAKA receipt.')),
                ('negligence', models.BooleanField(default=False, help_text='Manager negligence flag. Affects loss distribution in future.')),
                ('reason', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='inventory.lot')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'risk_event',
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='risk_event_tenant__b58564_idx'), models.Index(fields=['lot'], name='risk_event_lot_id_b714a6_idx')],
            },
        ),
    ]
