# Generated by Django 5.1.15 on 2026-04-13 12:04

import apps.core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Обязательство'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_account',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('operation_type', models.CharField(choices=[('sale', 'Продажа'), ('receipt', 'Приход'), ('payment', 'Оплата'), ('return', 'Возврат'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('debt_payment', 'Погашение долга')], max_length=20)),
                ('operation_id', models.IntegerField(help_text='ID of the source operation.')),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('is_reversal', models.BooleanField(default=False, help_text='True if this entry reverses another.')),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_journal_entry',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_journal_line',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('cash_in_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_in_debt_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_in_investor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_purchases', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_supplier_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_investor_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_cash_flow_summary',
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('investor_share', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_business_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('total_returns_count', models.IntegerField(default=0)),
                ('total_writeoffs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_daily_summary',
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_jou_tenant__0bb57b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'operation_type', 'operation_id'], name='finance_jou_tenant__056017_idx'),
        ),
    ]
