# Generated by Django 5.1.15 on 2026-04-18 09:20

import apps.core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Обязательство'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Расход')], max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_account',
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('kind', models.CharField(choices=[('cash', 'Касса наличных'), ('card_terminal', 'Карт-терминал'), ('bank', 'Банковский счёт')], default='cash', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='COA account for bookkeeping journal lines.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to='finance.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_cash_account',
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Расход')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateTimeField()),
                ('source_ref_type', models.CharField(blank=True, default='', help_text='E.g. "sale", "expense", "customer_payment".', max_length=50)),
                ('source_ref_id', models.IntegerField(blank=True, help_text='PK of the source object.', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.cashaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_cash_entry',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('cash_in_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_in_debt_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_in_investor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_purchases', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_supplier_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_out_investor_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_cash_flow_summary',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('to_currency', models.CharField(max_length=3)),
                ('effective_rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_out', to='finance.cashaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_in', to='finance.cashaccount')),
            ],
            options={
                'db_table': 'finance_currency_exchange',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('investor_share', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('net_business_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_sales_count', models.IntegerField(default=0)),
                ('total_returns_count', models.IntegerField(default=0)),
                ('total_writeoffs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(default='UZS', max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('source', models.CharField(choices=[('CBU', 'Central Bank of Uzbekistan'), ('MANUAL', 'Manual override')], default='CBU', max_length=12)),
                ('is_manual', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод')], max_length=10)),
                ('source_account_code', models.CharField(default='1000', max_length=20)),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount_uzs', models.DecimalField(decimal_places=2, max_digits=16)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_expense',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('operation_type', models.CharField(choices=[('sale', 'Продажа'), ('receipt', 'Приход'), ('payment', 'Оплата'), ('return', 'Возврат'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('debt_payment', 'Погашение долга')], max_length=20)),
                ('operation_id', models.IntegerField(help_text='ID of the source operation.')),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('is_reversal', models.BooleanField(default=False, help_text='True if this entry reverses another.')),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_journal_entry',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_journal_line',
            },
        ),
        migrations.CreateModel(
            name='OwnerContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='finance.cashaccount')),
            ],
            options={
                'db_table': 'finance_owner_contribution',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('plastik', 'Карт-терминал'), ('receivable_offset', 'Зачёт долга')], max_length=20)),
                ('account', models.ForeignKey(blank=True, help_text='Null for RECEIVABLE_OFFSET method.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.cashaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='customers.customer')),
            ],
            options={
                'db_table': 'finance_refund',
            },
        ),
    ]
