# Generated by Django 5.1.15 on 2026-04-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='return_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='sales.return'),
        ),
        migrations.AddField(
            model_name='refund',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['tenant', 'currency'], name='finance_cas_tenant__0a3491_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['account', 'date'], name='finance_cas_account_dec638_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['tenant', 'date'], name='finance_cas_tenant__1dae19_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['source_ref_type', 'source_ref_id'], name='finance_cas_source__5f2354_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cashflowsummary',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='currencyexchange',
            index=models.Index(fields=['tenant', 'date'], name='finance_cur_tenant__15bda0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('tenant', 'date')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['tenant', 'base_currency', 'quote_currency', 'rate_date'], name='finance_exc_tenant__c04cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['tenant', 'rate_date'], name='finance_exc_tenant__7072f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('tenant', 'base_currency', 'quote_currency', 'rate_date')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'occurred_at'], name='finance_exp_tenant__f4fbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['tenant', 'operation_currency'], name='finance_exp_tenant__4d4622_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'created_at'], name='finance_jou_tenant__0bb57b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'operation_type', 'operation_id'], name='finance_jou_tenant__056017_idx'),
        ),
        migrations.AddIndex(
            model_name='ownercontribution',
            index=models.Index(fields=['tenant', 'date'], name='finance_own_tenant__432657_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', 'date'], name='finance_ref_tenant__f2523e_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', 'date'], name='finance_ref_custome_64159a_idx'),
        ),
    ]
