# Generated by Django 5.1.15 on 2026-04-15 22:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_excel_i_tenant__f39388_idx_core_excel__tenant__dc35ee_idx_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowsummary',
            name='cash_out_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод')], max_length=10)),
                ('source_account_code', models.CharField(default='1000', max_length=20)),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount_uzs', models.DecimalField(decimal_places=2, max_digits=16)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_expense',
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='finance_exp_tenant__f4fbd9_idx'), models.Index(fields=['tenant', 'operation_currency'], name='finance_exp_tenant__4d4622_idx')],
            },
        ),
    ]
