# Generated by Django 5.1.15 on 2026-05-13 02:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('CASH_ACCOUNT', 'Cash account'), ('CAPITAL_POOL', 'Capital pool')], max_length=24)),
                ('source_id', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('PROCUREMENT_COST', 'Procurement cost'), ('SUPPLIER_PAYABLE', 'Supplier payable'), ('CAPITAL_CONTRIBUTION', 'Capital contribution'), ('DIVIDEND', 'Dividend')], max_length=32)),
                ('target_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=16)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=16)),
                ('paid_at', models.DateTimeField()),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.journalentry')),
                ('reversed_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_payments', to='finance.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(choices=[('PROCUREMENT_COST', 'Procurement cost'), ('SUPPLIER_PAYABLE', 'Supplier payable'), ('CAPITAL_CONTRIBUTION', 'Capital contribution'), ('DIVIDEND', 'Dividend')], max_length=32)),
                ('target_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_payment_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'paid_at'], name='finance_pay_tenant__8739c2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'source_type', 'source_id'], name='finance_pay_tenant__673769_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'target_type', 'target_id'], name='finance_pay_tenant__72a417_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status'], name='finance_pay_tenant__52374b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_finance_payment_idempotent'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='finance_pay_payment_370392_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['tenant', 'target_type', 'target_id'], name='finance_pay_tenant__053b99_idx'),
        ),
    ]
