# Generated by Codex on 2026-04-17

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_excel_i_tenant__f39388_idx_core_excel__tenant__dc35ee_idx_and_more'),
        ('finance', '0002_cashflowsummary_cash_out_expenses_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(default='UZS', max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('source', models.CharField(choices=[('CBU', 'Central Bank of Uzbekistan'), ('MANUAL', 'Manual override')], default='CBU', max_length=12)),
                ('is_manual', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_exchange_rate',
                'indexes': [models.Index(fields=['tenant', 'base_currency', 'quote_currency', 'rate_date'], name='finance_exc_tenant__2250d2_idx'), models.Index(fields=['tenant', 'rate_date'], name='finance_exc_tenant__43e84a_idx')],
                'unique_together': {('tenant', 'base_currency', 'quote_currency', 'rate_date')},
            },
        ),
    ]
