# Generated by Django 5.1.15 on 2026-05-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source_type',
            field=models.CharField(choices=[('CASH_ACCOUNT', 'Cash account'), ('CAPITAL_POOL', 'Capital pool'), ('EXTERNAL_PARTNER', 'External partner')], max_length=24),
        ),
    ]
