# Generated by Django 5.1.15 on 2026-05-22 00:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0004_alter_payment_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.cashaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.cashaccount')),
            ],
            options={
                'db_table': 'finance_cash_transfer',
                'indexes': [models.Index(fields=['tenant', 'date'], name='finance_cas_tenant__0e4c71_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawings', to='finance.cashaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'finance_owner_drawing',
                'indexes': [models.Index(fields=['tenant', 'date'], name='finance_own_tenant__06d6a1_idx')],
            },
        ),
    ]
