# Generated by Django 5.1.15 on 2026-05-22 00:20

from django.db import migrations


def seed_coa_3001(apps, schema_editor):
    Account = apps.get_model('finance', 'Account')
    Business = apps.get_model('core', 'Business')
    for tenant in Business.objects.all():
        Account.objects.get_or_create(
            tenant=tenant,
            code='3001',
            defaults={
                'name': 'Изъятие капитала владельца',
                'account_type': 'equity',
                'is_system': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_owner_drawing_cash_transfer'),
    ]

    operations = [
        migrations.RunPython(seed_coa_3001, migrations.RunPython.noop),
    ]
