# Generated by Django 5.1.15 on 2026-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_seed_coa_3001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='kind',
            field=models.CharField(choices=[('cash', 'Касса наличных'), ('card_terminal', 'Карт-терминал'), ('bank', 'Банковский счёт'), ('agreement_capital', 'Капитал инвест-договора (пул)')], default='cash', max_length=20),
        ),
    ]
