# Generated by Django 5.1.15 on 2026-06-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_currencyexchange_fx_rate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('receipt', 'Приход'), ('payment', 'Оплата'), ('return', 'Возврат'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('debt_payment', 'Погашение долга'), ('advance_settle', 'Погашение капитального аванса')], max_length=20),
        ),
    ]
