# Generated by Django 5.1.15 on 2026-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_journalentry_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Продажа'), ('receipt', 'Приход'), ('payment', 'Оплата'), ('return', 'Возврат'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('debt_payment', 'Погашение долга'), ('advance_settle', 'Погашение капитального аванса'), ('capital_return', 'Возврат капитала'), ('profit_distrib', 'Распределение прибыли'), ('venture_debt_repay', 'Погашение долга венчуру')], max_length=20),
        ),
    ]
