# Generated by Django 5.1.15 on 2026-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_journalentry_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='kind',
            field=models.CharField(choices=[('cash', 'Касса наличных'), ('card_terminal', 'Карт-терминал'), ('bank', 'Банковский счёт'), ('agreement_capital', 'Капитал инвест-договора (пул)'), ('fund_capital', 'Капитал инвестиционного фонда (пул)')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_type',
            field=models.CharField(choices=[('PROCUREMENT_COST', 'Procurement cost'), ('SUPPLIER_PAYABLE', 'Supplier payable'), ('CAPITAL_CONTRIBUTION', 'Capital contribution'), ('FUND_CONTRIBUTION', 'Fund contribution'), ('DIVIDEND', 'Dividend')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='target_type',
            field=models.CharField(choices=[('PROCUREMENT_COST', 'Procurement cost'), ('SUPPLIER_PAYABLE', 'Supplier payable'), ('CAPITAL_CONTRIBUTION', 'Capital contribution'), ('FUND_CONTRIBUTION', 'Fund contribution'), ('DIVIDEND', 'Dividend')], max_length=32),
        ),
    ]
