# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='productsupplier',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributevalue'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='categorycharacteristictemplate',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='catalog_pro_tenant__bfe37a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='catalog_pro_tenant__750d04_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'product', 'is_active'], name='catalog_pro_tenant__8be4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['supplier', '-last_received_at'], name='catalog_pro_supplie_7c4c50_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['tenant', 'supplier'], name='catalog_pro_tenant__ad1dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='productsupplier',
            index=models.Index(fields=['tenant', 'product_variant'], name='catalog_pro_tenant__33ca8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product_variant', 'supplier'), name='uq_product_supplier_pair'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('variant', 'attribute_value')},
        ),
    ]
