# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='1-based ordinal within the schedule.')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('PAID', 'Оплачен'), ('OVERDUE', 'Просрочен'), ('CANCELLED', 'Отменён')], default='PENDING', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('procurement_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='partnerships.procurementterms')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'suppliers_payment_schedule',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='How much business owes this supplier (A/P).', max_digits=14)),
                ('default_payment_terms', models.CharField(choices=[('PREPAID', 'Полная предоплата'), ('PARTIAL', 'Частичная оплата'), ('DEFERRED', 'Отсрочка'), ('INSTALLMENT', 'Рассрочка'), ('CONSIGNMENT', 'Консигнация (реализация)')], default='PREPAID', help_text='Default payment terms suggested when creating a procurement.', max_length=16)),
                ('default_currency', models.CharField(default='UZS', help_text='Default obligation currency for this supplier.', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'suppliers_supplier',
            },
        ),
        migrations.CreateModel(
            name='ConsignmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rule_type', models.CharField(choices=[('margin', 'Фиксированная маржа'), ('commission', 'Процент комиссии')], max_length=20)),
                ('rule_value', models.DecimalField(decimal_places=4, help_text='Margin amount or commission percentage.', max_digits=8)),
                ('damage_liability_on_business', models.BooleanField(default=True, help_text='If True, damage/loss of consignment goods is on business.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_agreements', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'suppliers_consignment_agreement',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Computed = original_amount - paid_amount (kept consistent in services).', max_digits=16)),
                ('currency_of_obligation', models.CharField(default='UZS', max_length=3)),
                ('fx_rate_at_obligation', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Snapshot of FX rate at the moment the obligation was created.', max_digits=16)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('PARTIALLY_PAID', 'Частично оплачен'), ('FULLY_PAID', 'Полностью оплачен'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=16)),
                ('reason', models.CharField(choices=[('PROCUREMENT', 'Из приёмки'), ('AMENDMENT', 'Изменение условий'), ('PENALTY', 'Штраф/пеня')], default='PROCUREMENT', max_length=16)),
                ('deadline_date', models.DateField(blank=True, help_text='For DEFERRED procurements; may be null for INSTALLMENT (use schedule).', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='partnerships.procurement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'suppliers_payable',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('operation_currency', models.CharField(default='UZS', max_length=3)),
                ('operation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('fx_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('functional_amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод'), ('mixed', 'Смешанный (мульти-касса)')], max_length=10)),
                ('allocations', models.JSONField(blank=True, help_text='Optional multi-cash allocation: [{cash_account_id, amount, currency}, ...]. Empty/null for single-cash payments.', null=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplierpayable')),
                ('schedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.paymentschedule')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'suppliers_payment',
            },
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='suppliers_p_tenant__754b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['procurement_terms', 'sequence_number'], name='suppliers_p_procure_fb33a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedule',
            constraint=models.UniqueConstraint(fields=('procurement_terms', 'sequence_number'), name='uq_payment_schedule_sequence'),
        ),
        migrations.AddIndex(
            model_name='supplierpayable',
            index=models.Index(fields=['tenant', 'supplier', 'status'], name='suppliers_p_tenant__ab1566_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayable',
            index=models.Index(fields=['tenant', 'status'], name='suppliers_p_tenant__6fc2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayable',
            index=models.Index(fields=['tenant', 'deadline_date'], name='suppliers_p_tenant__cb58d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayable',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', Decimal('0'))), name='supplier_payable_paid_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayable',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', Decimal('0'))), name='supplier_payable_remaining_non_negative'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', 'supplier', 'date'], name='suppliers_p_tenant__65d204_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['tenant', 'payable'], name='suppliers_p_tenant__525361_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_supplier_payment_idempotent'),
        ),
    ]
