# Generated by Django 5.1.15 on 2026-05-13 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_paymentallocation_and_more'),
        ('partnerships', '0003_remove_procurement_partnership_tenant__ec1798_idx_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayable',
            name='settlement',
            field=models.ForeignKey(blank=True, help_text='E07 supplier settlement source. Nullable during reset for older payables.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='partnerships.procurementterms'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='E07 generic payment document backing this supplier payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_records', to='finance.payment'),
        ),
        migrations.AlterField(
            model_name='consignmentagreement',
            name='rule_type',
            field=models.CharField(choices=[('FIXED_SUPPLIER_PRICE', 'Фиксированная цена поставщика'), ('margin', 'Фиксированная маржа'), ('commission', 'Процент комиссии')], max_length=20),
        ),
    ]
