# Generated by Django 5.1.15 on 2026-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplierpayable_settlement_supplierpayment_payment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierpayable',
            name='supplier_payable_paid_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='supplierpayable',
            name='supplier_payable_remaining_non_negative',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='outstanding_balance',
        ),
        migrations.RemoveField(
            model_name='supplierpayable',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='supplierpayable',
            name='remaining_amount',
        ),
    ]
