# Generated by Django 5.1.15 on 2026-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplierpayable_supplier_payable_paid_amount_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayable',
            name='reason',
            field=models.CharField(choices=[('PROCUREMENT', 'Из приёмки'), ('AMENDMENT', 'Изменение условий'), ('PENALTY', 'Штраф/пеня'), ('CONSIGNMENT_SALE', 'Продажа консигнации')], default='PROCUREMENT', max_length=16),
        ),
    ]
