# Generated by Django 5.1.15 on 2026-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_consignment_sale_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
