# Generated by Django 5.1.15 on 2026-05-13 00:47

import apps.core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CONFIRMED', 'Подтверждён'), ('CANCELLED', 'Отменён')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_consignment_return',
            },
        ),
        migrations.CreateModel(
            name='ConsignmentReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity from the lot being processed under this disposition.', max_digits=14)),
                ('disposition', models.CharField(choices=[('RETURN_TO_SUPPLIER', 'Возврат поставщику'), ('DISPOSE_SUPPLIER_LOSS', 'Списание (на поставщике)'), ('DISPOSE_BUSINESS_LOSS', 'Списание (на бизнесе)'), ('CONVERT_TO_OWN', 'Перевод в собственность')], max_length=24)),
                ('agreed_price_per_unit', models.DecimalField(decimal_places=6, help_text='Agreed unit price for the disposition. For RETURN/DISPOSE_*: amount of payable reduction per unit. For CONVERT_TO_OWN: buyout price per unit.', max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'partnerships_consignment_return_line',
            },
        ),
        migrations.CreateModel(
            name='ContractPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('planned_capital_share', models.DecimalField(decimal_places=2, help_text='Planned capital in contract currency', max_digits=14)),
                ('profit_share', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Derived profit ratio (snapshot) — recomputed on receive', max_digits=7)),
            ],
            options={
                'db_table': 'partnerships_contract_partner',
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('paid_from_account_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'partnerships_dividend_payment',
            },
        ),
        migrations.CreateModel(
            name='InvestmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('ACTIVE', 'Активен'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('mudaraba_ratio', models.DecimalField(decimal_places=6, help_text='m in [0..1]; investor profit = capital * m', max_digits=8)),
                ('loss_rule', models.CharField(choices=[('BY_CAPITAL', 'По доле капитала')], default='BY_CAPITAL', max_length=20)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('balances', models.JSONField(default=dict, help_text='Map<currency, decimal_string>')),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_investment_agreement',
            },
        ),
        migrations.CreateModel(
            name='InvestmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mudaraba_ratio', models.DecimalField(decimal_places=6, help_text='m in [0..1]; investor profit = capital * m', max_digits=8)),
                ('loss_rule', models.CharField(choices=[('BY_CAPITAL', 'По доле капитала')], default='BY_CAPITAL', max_length=20)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
            ],
            options={
                'db_table': 'partnerships_investment_contract',
            },
        ),
        migrations.CreateModel(
            name='PartnerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Snapshot rate to UZS for this ledger entry.', max_digits=14)),
                ('functional_amount_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Entry amount converted to tenant functional currency (UZS).', max_digits=20)),
                ('entry_type', models.CharField(choices=[('CAPITAL_IN', 'Внос капитала'), ('CAPITAL_OUT', 'Вывод капитала'), ('PROFIT_ACCRUED', 'Начислена прибыль'), ('PROFIT_REVERSED', 'Сторно прибыли'), ('DIVIDEND_PAID', 'Выплачен дивиденд'), ('LOSS_INCURRED', 'Зафиксирован убыток')], max_length=20)),
                ('source_ref', models.CharField(blank=True, default='', help_text='E.g. "sale_line:42", "risk_event:7", "contribution:3"', max_length=100)),
            ],
            options={
                'db_table': 'partnerships_ledger_entry',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('procurement_type', models.CharField(choices=[('OWN_FUNDS', 'Собственные средства'), ('PARTNERSHIP', 'Партнёрский'), ('MUSHARAKA', 'Мушарака'), ('DISTRIBUTOR', 'Дистрибуторский')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('PARTIALLY_RECEIVED', 'Частично оприходовано'), ('RECEIVED', 'Получен'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_procurement',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcurementBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balances', models.JSONField(default=dict, help_text='Map<currency, decimal_string>')),
            ],
            options={
                'db_table': 'partnerships_procurement_balance',
            },
        ),
        migrations.CreateModel(
            name='ProcurementBalanceExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('from_currency', models.CharField(default='UZS', max_length=3)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('to_currency', models.CharField(default='USD', max_length=3)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'partnerships_balance_exchange',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expense_type', models.CharField(choices=[('LOGISTICS', 'Логистика'), ('CUSTOMS', 'Таможня'), ('FEE', 'Комиссия'), ('OTHER', 'Прочее')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('allocation_method', models.CharField(choices=[('BY_VALUE', 'Пропорционально стоимости'), ('BY_QUANTITY', 'Пропорционально количеству'), ('BY_WEIGHT', 'Пропорционально весу')], default='BY_VALUE', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PAID', 'Оплачено'), ('RECEIVED', 'Оприходовано')], default='DRAFT', max_length=16)),
            ],
            options={
                'db_table': 'partnerships_procurement_expense',
            },
        ),
        migrations.CreateModel(
            name='ProcurementExpenseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_procurement_expense_target',
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_purchase_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PAID', 'Оплачено'), ('RECEIVED', 'Оприходовано')], default='DRAFT', max_length=16)),
            ],
            options={
                'db_table': 'partnerships_procurement_item',
            },
        ),
        migrations.CreateModel(
            name='ProcurementPartnerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_partner_ledger',
            },
        ),
        migrations.CreateModel(
            name='ProcurementReceiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('total_inventory_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'db_table': 'partnerships_procurement_receive_batch',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementReceiveBatchCapitalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('amount_contract_currency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('capital_share', models.DecimalField(decimal_places=6, max_digits=8)),
                ('profit_share', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
            options={
                'db_table': 'partnerships_procurement_receive_batch_capital_allocation',
            },
        ),
        migrations.CreateModel(
            name='ProcurementReceiveBatchExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('allocated_amount_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'partnerships_procurement_receive_batch_expense',
            },
        ),
        migrations.CreateModel(
            name='ProcurementReceiveBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_purchase_price_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('allocated_expense_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('landed_cost_per_unit_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'partnerships_procurement_receive_batch_line',
            },
        ),
        migrations.CreateModel(
            name='ProcurementTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('PREPAID', 'Полная предоплата'), ('PARTIAL', 'Частичная оплата'), ('DEFERRED', 'Отсрочка'), ('INSTALLMENT', 'Рассрочка'), ('CONSIGNMENT', 'Консигнация')], max_length=16)),
                ('currency_of_obligation', models.CharField(default='UZS', max_length=3)),
                ('fx_rate_at_obligation', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Snapshot of FX rate at obligation date; not revalued.', max_digits=16)),
                ('total_amount_due', models.DecimalField(decimal_places=2, help_text='Total obligation in `currency_of_obligation` (Σ items × prices × fx).', max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('OPEN', 'Открыты'), ('PARTIALLY_PAID', 'Частично оплачены'), ('FULLY_PAID', 'Полностью оплачены'), ('CANCELLED', 'Отменены')], default='OPEN', max_length=16)),
                ('deadline_date', models.DateField(blank=True, help_text='Only for DEFERRED type. Null otherwise (schedule covers INSTALLMENT).', null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'partnerships_procurement_terms',
            },
        ),
        migrations.CreateModel(
            name='ProcurementTermsAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amended_at', models.DateTimeField()),
                ('change_payload', models.JSONField(help_text='Snapshot {before: {...}, after: {...}} of changed fields.')),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'partnerships_procurement_terms_amendment',
            },
        ),
        migrations.CreateModel(
            name='AgreementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('TO_PROCUREMENT', 'В приход'), ('FROM_PROCUREMENT', 'Из прихода')], default='TO_PROCUREMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_agreement_allocation',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_contributions', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_agreement_contribution',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('planned_capital_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_share', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=7)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_memberships', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_agreement_partner',
            },
        ),
        migrations.CreateModel(
            name='AgreementWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_withdrawals', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_agreement_withdrawal',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_balance_contribution',
            },
        ),
        migrations.CreateModel(
            name='BalanceWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(blank=True, help_text='Set when withdrawal attributed to a specific partner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_balance_withdrawal',
            },
        ),
    ]
