# Generated by Django 5.1.15 on 2026-04-18 09:07

import apps.core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('procurement_type', models.CharField(choices=[('OWN_FUNDS', 'Собственные средства'), ('PARTNERSHIP', 'Партнёрский'), ('MUSHARAKA', 'Мушарака'), ('DISTRIBUTOR', 'Дистрибуторский')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('RECEIVED', 'Получен'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvestmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mudaraba_ratio', models.DecimalField(decimal_places=4, help_text='m in [0..1]; investor profit = capital * m', max_digits=6)),
                ('loss_rule', models.CharField(choices=[('BY_CAPITAL', 'По доле капитала')], default='BY_CAPITAL', max_length=20)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='partnerships.procurement')),
            ],
            options={
                'db_table': 'partnerships_investment_contract',
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('paid_from_account_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='partnerships.procurement')),
            ],
            options={
                'db_table': 'partnerships_dividend_payment',
            },
        ),
        migrations.CreateModel(
            name='ProcurementBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balances', models.JSONField(default=dict, help_text='Map<currency, decimal_string>')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_balance',
            },
        ),
        migrations.CreateModel(
            name='BalanceWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(blank=True, help_text='Set when withdrawal attributed to a specific partner', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partnerships.procurementbalance')),
            ],
            options={
                'db_table': 'partnerships_balance_withdrawal',
            },
        ),
        migrations.CreateModel(
            name='BalanceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='partnerships.procurementbalance')),
            ],
            options={
                'db_table': 'partnerships_balance_contribution',
            },
        ),
        migrations.CreateModel(
            name='ProcurementExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expense_type', models.CharField(choices=[('LOGISTICS', 'Логистика'), ('CUSTOMS', 'Таможня'), ('FEE', 'Комиссия'), ('OTHER', 'Прочее')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('allocation_method', models.CharField(choices=[('BY_VALUE', 'Пропорционально стоимости'), ('BY_QUANTITY', 'Пропорционально количеству'), ('BY_WEIGHT', 'Пропорционально весу')], default='BY_VALUE', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_expense',
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partnerships.procurement')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_items', to='catalog.productvariant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_item',
            },
        ),
        migrations.CreateModel(
            name='ProcurementPartnerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='core.partner')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_ledgers', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_partner_ledger',
            },
        ),
        migrations.CreateModel(
            name='PartnerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('entry_type', models.CharField(choices=[('CAPITAL_IN', 'Внос капитала'), ('CAPITAL_OUT', 'Вывод капитала'), ('PROFIT_ACCRUED', 'Начислена прибыль'), ('PROFIT_REVERSED', 'Сторно прибыли'), ('DIVIDEND_PAID', 'Выплачен дивиденд'), ('LOSS_INCURRED', 'Зафиксирован убыток')], max_length=20)),
                ('source_ref', models.CharField(blank=True, default='', help_text='E.g. "sale_line:42", "risk_event:7", "contribution:3"', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='partnerships.procurementpartnerledger')),
            ],
            options={
                'db_table': 'partnerships_ledger_entry',
            },
        ),
        migrations.CreateModel(
            name='ContractPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('planned_capital_share', models.DecimalField(decimal_places=2, help_text='Planned capital in contract currency', max_digits=14)),
                ('profit_share', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Derived profit ratio (snapshot) — recomputed on receive', max_digits=7)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_memberships', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_partners', to='partnerships.investmentcontract')),
            ],
            options={
                'db_table': 'partnerships_contract_partner',
                'indexes': [models.Index(fields=['contract'], name='partnership_contrac_5d6260_idx'), models.Index(fields=['partner'], name='partnership_partner_eb8042_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'partner', 'role'), name='uq_contract_partner_role')],
            },
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'status'], name='partnership_tenant__6d8f79_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'procurement_type'], name='partnership_tenant__ec1798_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_procurement_idempotent'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['partner', 'date'], name='partnership_partner_d6760d_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['procurement'], name='partnership_procure_68ef56_idx'),
        ),
        migrations.AddIndex(
            model_name='balancewithdrawal',
            index=models.Index(fields=['balance'], name='partnership_balance_71b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='balancecontribution',
            index=models.Index(fields=['balance'], name='partnership_balance_d3c00f_idx'),
        ),
        migrations.AddIndex(
            model_name='balancecontribution',
            index=models.Index(fields=['partner'], name='partnership_partner_c8ec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpense',
            index=models.Index(fields=['procurement'], name='partnership_procure_b5b7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementitem',
            index=models.Index(fields=['procurement'], name='partnership_procure_ddccd4_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementpartnerledger',
            index=models.Index(fields=['tenant', 'partner'], name='partnership_tenant__fc7287_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementpartnerledger',
            constraint=models.UniqueConstraint(fields=('procurement', 'partner'), name='uq_ledger_procurement_partner'),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['ledger', 'entry_type'], name='partnership_ledger__970a26_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['tenant', 'date'], name='partnership_tenant__42d3e2_idx'),
        ),
    ]
