# Generated by Django 5.1.15 on 2026-05-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('inventory', '0002_initial'),
        ('partnerships', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentreturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_returns', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='consignmentreturn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='consignmentreturnline',
            name='consignment_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='partnerships.consignmentreturn'),
        ),
        migrations.AddField(
            model_name='consignmentreturnline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_return_lines', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='consignmentreturnline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='contractpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_memberships', to='core.partner'),
        ),
        migrations.AddField(
            model_name='contractpartner',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='core.partner'),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='investmentagreement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_agreements', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='investmentagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='agreementpartner',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='investmentcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='contractpartner',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_partners', to='partnerships.investmentcontract'),
        ),
        migrations.AddField(
            model_name='partnerledgerentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='investmentcontract',
            name='procurement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='consignmentreturn',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_returns', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementbalance',
            name='procurement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementbalance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='balancewithdrawal',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partnerships.procurementbalance'),
        ),
        migrations.AddField(
            model_name='balancecontribution',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='partnerships.procurementbalance'),
        ),
        migrations.AddField(
            model_name='procurementbalanceexchange',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='partnerships.procurementbalance'),
        ),
        migrations.AddField(
            model_name='procurementbalanceexchange',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementexpense',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementexpense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='partnerships.procurementexpense'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_targets', to='partnerships.procurementitem'),
        ),
        migrations.AddField(
            model_name='procurementpartnerledger',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='core.partner'),
        ),
        migrations.AddField(
            model_name='procurementpartnerledger',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_ledgers', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementpartnerledger',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='partnerledgerentry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='partnerships.procurementpartnerledger'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatch',
            name='procurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_batches', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_receive_batches', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchcapitalallocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_allocations', to='partnerships.procurementreceivebatch'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchcapitalallocation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_receive_batch_allocations', to='core.partner'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchcapitalallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchexpense',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='partnerships.procurementreceivebatch'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_batch_expenses', to='partnerships.procurementexpense'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchexpense',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='partnerships.procurementreceivebatch'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_batch_lines', to='partnerships.procurementitem'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receive_batch_line', to='inventory.lot'),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementterms',
            name='consignment_agreement',
            field=models.ForeignKey(blank=True, help_text='Only for CONSIGNMENT type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_terms', to='suppliers.consignmentagreement'),
        ),
        migrations.AddField(
            model_name='procurementterms',
            name='procurement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='partnerships.procurement'),
        ),
        migrations.AddField(
            model_name='procurementterms',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementtermsamendment',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_terms_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementtermsamendment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='procurementtermsamendment',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='partnerships.procurementterms'),
        ),
        migrations.AddIndex(
            model_name='consignmentreturnline',
            index=models.Index(fields=['consignment_return'], name='partnership_consign_df3dae_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentreturnline',
            index=models.Index(fields=['lot'], name='partnership_lot_id_279ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentagreement',
            index=models.Index(fields=['tenant', 'status'], name='partnership_tenant__5e2d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentagreement',
            index=models.Index(fields=['tenant', 'opened_at'], name='partnership_tenant__e613e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_investment_agreement_idempotent'),
        ),
        migrations.AddIndex(
            model_name='agreementwithdrawal',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_82f1df_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementwithdrawal',
            index=models.Index(fields=['partner'], name='partnership_partner_d6ba2c_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementpartner',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_adfcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementpartner',
            index=models.Index(fields=['partner'], name='partnership_partner_5b63e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementpartner',
            constraint=models.UniqueConstraint(fields=('agreement', 'partner', 'role'), name='uq_agreement_partner_role'),
        ),
        migrations.AddIndex(
            model_name='agreementcontribution',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_823e72_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcontribution',
            index=models.Index(fields=['partner'], name='partnership_partner_b5b91a_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpartner',
            index=models.Index(fields=['contract'], name='partnership_contrac_5d6260_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpartner',
            index=models.Index(fields=['partner'], name='partnership_partner_eb8042_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractpartner',
            constraint=models.UniqueConstraint(fields=('contract', 'partner', 'role'), name='uq_contract_partner_role'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'status'], name='partnership_tenant__6d8f79_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'procurement_type'], name='partnership_tenant__ec1798_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'agreement'], name='partnership_tenant__9f89d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_procurement_idempotent'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['partner', 'date'], name='partnership_partner_d6760d_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendpayment',
            index=models.Index(fields=['procurement'], name='partnership_procure_68ef56_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentreturn',
            index=models.Index(fields=['tenant', 'procurement'], name='partnership_tenant__afd61c_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentreturn',
            index=models.Index(fields=['tenant', 'status', 'return_date'], name='partnership_tenant__cf8967_idx'),
        ),
        migrations.AddConstraint(
            model_name='consignmentreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_consignment_return_idempotent'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_96da56_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['procurement'], name='partnership_procure_8280d0_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['partner'], name='partnership_partner_177016_idx'),
        ),
        migrations.AddIndex(
            model_name='balancewithdrawal',
            index=models.Index(fields=['balance'], name='partnership_balance_71b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='balancecontribution',
            index=models.Index(fields=['balance'], name='partnership_balance_d3c00f_idx'),
        ),
        migrations.AddIndex(
            model_name='balancecontribution',
            index=models.Index(fields=['partner'], name='partnership_partner_c8ec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementbalanceexchange',
            index=models.Index(fields=['balance'], name='partnership_balance_8b2668_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpense',
            index=models.Index(fields=['procurement'], name='partnership_procure_b5b7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpense',
            index=models.Index(fields=['procurement', 'status'], name='partnership_procure_ab1e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementitem',
            index=models.Index(fields=['procurement'], name='partnership_procure_ddccd4_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementitem',
            index=models.Index(fields=['procurement', 'status'], name='partnership_procure_cda147_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpensetarget',
            index=models.Index(fields=['expense'], name='partnership_expense_b7bd75_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpensetarget',
            index=models.Index(fields=['item'], name='partnership_item_id_a6073a_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementexpensetarget',
            constraint=models.UniqueConstraint(fields=('expense', 'item'), name='uq_procurement_expense_target'),
        ),
        migrations.AddIndex(
            model_name='procurementpartnerledger',
            index=models.Index(fields=['tenant', 'partner'], name='partnership_tenant__fc7287_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementpartnerledger',
            constraint=models.UniqueConstraint(fields=('procurement', 'partner'), name='uq_ledger_procurement_partner'),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['ledger', 'entry_type'], name='partnership_ledger__970a26_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerledgerentry',
            index=models.Index(fields=['tenant', 'date'], name='partnership_tenant__42d3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatch',
            index=models.Index(fields=['procurement', 'received_at'], name='partnership_procure_f0a2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatch',
            index=models.Index(fields=['warehouse'], name='partnership_warehou_3f31c8_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchcapitalallocation',
            index=models.Index(fields=['batch'], name='partnership_batch_i_19d320_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchcapitalallocation',
            index=models.Index(fields=['partner'], name='partnership_partner_32d0cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementreceivebatchcapitalallocation',
            constraint=models.UniqueConstraint(fields=('batch', 'partner'), name='uq_receive_batch_capital_partner'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchexpense',
            index=models.Index(fields=['batch'], name='partnership_batch_i_2b88d7_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchexpense',
            index=models.Index(fields=['expense'], name='partnership_expense_cebc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchline',
            index=models.Index(fields=['batch'], name='partnership_batch_i_5e6e1d_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchline',
            index=models.Index(fields=['item'], name='partnership_item_id_bf9414_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementreceivebatchline',
            index=models.Index(fields=['lot'], name='partnership_lot_id_776a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementterms',
            index=models.Index(fields=['tenant', 'type', 'status'], name='partnership_tenant__cefdad_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementterms',
            index=models.Index(fields=['tenant', 'status', 'deadline_date'], name='partnership_tenant__85b2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementtermsamendment',
            index=models.Index(fields=['terms', 'amended_at'], name='partnership_terms_i_cb4bc8_idx'),
        ),
    ]
