# Generated by Django 5.1.15 on 2026-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('core', '0001_initial'),
        ('partnerships', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='procurement',
            name='partnership_tenant__ec1798_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementexpense',
            name='partnership_procure_ab1e4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='procurementitem',
            name='partnership_procure_cda147_idx',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='procurement_type',
        ),
        migrations.RemoveField(
            model_name='procurementexpense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='status',
        ),
        migrations.AddField(
            model_name='investmentagreement',
            name='legal_mode',
            field=models.CharField(blank=True, choices=[('MUDARABA', 'Мудараба'), ('MUSHARAKA', 'Мушарака'), ('HYBRID', 'Гибрид')], help_text='Legal/contract label only; not a procurement type.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='funding_source',
            field=models.CharField(choices=[('OWN_FUNDS', 'Собственные средства'), ('PARTNERSHIP', 'Партнёрский капитал')], default='OWN_FUNDS', help_text='E07 target funding axis.', max_length=20),
        ),
        migrations.AddField(
            model_name='procurementexpense',
            name='lifecycle_state',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('READY_FOR_RECEIVE', 'Готово к приёмке'), ('RECEIVED', 'Оприходовано'), ('CANCELLED', 'Отменено')], default='DRAFT', max_length=24),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='lifecycle_state',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('READY_FOR_RECEIVE', 'Готово к приёмке'), ('RECEIVED', 'Оприходовано'), ('CANCELLED', 'Отменено')], default='DRAFT', max_length=24),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'funding_source'], name='partnership_tenant__d02b95_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpense',
            index=models.Index(fields=['procurement', 'lifecycle_state'], name='partnership_procure_9b5500_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementitem',
            index=models.Index(fields=['procurement', 'lifecycle_state'], name='partnership_procure_55c678_idx'),
        ),
    ]
