# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0003_remove_procurement_partnership_tenant__ec1798_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='primary_currency',
            field=models.CharField(
                default='UZS',
                help_text='Workspace display/default currency for item and expense drafts.',
                max_length=3,
            ),
        ),
    ]
