# Generated by Django 5.1.15 on 2026-05-18 06:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0004_procurement_primary_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система')], default='BUSINESS_RECORDED', max_length=24)),
                ('related_model', models.CharField(blank=True, default='', max_length=80)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'partnerships_agreement_event',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система')], default='BUSINESS_RECORDED', max_length=24)),
                ('confirmation_status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('DISPUTED', 'Оспаривается'), ('CANCELLED', 'Отменено')], default='CONFIRMED', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_capital_commitment',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='actor_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations_acted', to='core.partner'),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('DISPUTED', 'Оспаривается'), ('CANCELLED', 'Отменено')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementallocation',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='actor_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_contributions_acted', to='core.partner'),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('DISPUTED', 'Оспаривается'), ('CANCELLED', 'Отменено')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_contributions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='actor_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_withdrawals_acted', to='core.partner'),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('DISPUTED', 'Оспаривается'), ('CANCELLED', 'Отменено')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_withdrawals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='investmentagreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROPOSED', 'Предложен'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонён'), ('OPEN', 'Открыт'), ('ACTIVE', 'Активен'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['confirmation_status'], name='partnership_confirm_22e7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['tenant', 'client_request_id'], name='partnership_tenant__720adb_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcontribution',
            index=models.Index(fields=['confirmation_status'], name='partnership_confirm_40e151_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementwithdrawal',
            index=models.Index(fields=['confirmation_status'], name='partnership_confirm_b3da63_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementcontribution',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_agreement_contribution_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='agreementwithdrawal',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_agreement_withdrawal_idempotent'),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='actor_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_events', to='core.partner'),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='capitalcommitment',
            name='actor_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_commitments_acted', to='core.partner'),
        ),
        migrations.AddField(
            model_name='capitalcommitment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='capitalcommitment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_commitments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitalcommitment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_commitments', to='core.partner'),
        ),
        migrations.AddField(
            model_name='capitalcommitment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['agreement', 'event_type'], name='partnership_agreeme_2c938f_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='partnership_tenant__6381a3_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementevent',
            index=models.Index(fields=['related_model', 'related_id'], name='partnership_related_2cd240_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcommitment',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_76aae8_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcommitment',
            index=models.Index(fields=['partner'], name='partnership_partner_2f55c2_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcommitment',
            index=models.Index(fields=['confirmation_status'], name='partnership_confirm_a5e48f_idx'),
        ),
        migrations.AddConstraint(
            model_name='capitalcommitment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_capital_commitment_idempotent'),
        ),
    ]
