# Generated by Django 5.1.15 on 2026-05-18 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payment_source_type'),
        ('partnerships', '0005_agreementevent_capitalcommitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendpayment',
            name='paid_from_account_id',
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='paid_from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.cashaccount'),
        ),
    ]
