# Generated by Django 5.1.15 on 2026-04-27 14:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_legacy_agreement_wrappers(apps, schema_editor):
    Procurement = apps.get_model('partnerships', 'Procurement')
    InvestmentContract = apps.get_model('partnerships', 'InvestmentContract')
    ContractPartner = apps.get_model('partnerships', 'ContractPartner')
    InvestmentAgreement = apps.get_model('partnerships', 'InvestmentAgreement')
    AgreementPartner = apps.get_model('partnerships', 'AgreementPartner')

    procurements = (
        Procurement.objects
        .filter(agreement__isnull=True, procurement_type__in=['PARTNERSHIP', 'MUSHARAKA'])
        .order_by('id')
    )
    for procurement in procurements.iterator():
        contract = InvestmentContract.objects.filter(procurement_id=procurement.id).first()
        if contract is None:
            continue

        status = 'ACTIVE'
        closed_at = None
        if procurement.status == 'CANCELLED':
            status = 'CANCELLED'
            closed_at = procurement.closed_at
        elif procurement.status == 'CLOSED':
            status = 'CLOSED'
            closed_at = procurement.closed_at

        agreement = InvestmentAgreement.objects.create(
            tenant_id=procurement.tenant_id,
            status=status,
            opened_at=procurement.opened_at,
            closed_at=closed_at,
            supplier_id=procurement.supplier_id,
            mudaraba_ratio=contract.mudaraba_ratio,
            loss_rule=contract.loss_rule,
            planned_budget=contract.planned_budget,
            currency=contract.currency,
            balances={},
            notes='Legacy wrapper for a standalone procurement.',
        )
        for member in ContractPartner.objects.filter(contract_id=contract.id).iterator():
            AgreementPartner.objects.create(
                tenant_id=procurement.tenant_id,
                agreement_id=agreement.id,
                partner_id=member.partner_id,
                role=member.role,
                planned_capital_share=member.planned_capital_share,
                profit_share=member.profit_share,
            )

        procurement.agreement_id = agreement.id
        procurement.save(update_fields=['agreement_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investor_invites'),
        ('partnerships', '0005_procurement_balance_exchange'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementExpenseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_procurement_expense_target',
            },
        ),
        migrations.CreateModel(
            name='InvestmentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Открыт'), ('ACTIVE', 'Активен'), ('CLOSED', 'Закрыт'), ('CANCELLED', 'Отменён')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('mudaraba_ratio', models.DecimalField(decimal_places=6, help_text='m in [0..1]; investor profit = capital * m', max_digits=8)),
                ('loss_rule', models.CharField(choices=[('BY_CAPITAL', 'По доле капитала')], default='BY_CAPITAL', max_length=20)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('balances', models.JSONField(default=dict, help_text='Map<currency, decimal_string>')),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_agreements', to='suppliers.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_investment_agreement',
            },
        ),
        migrations.CreateModel(
            name='AgreementWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_withdrawals', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='partnerships.investmentagreement')),
            ],
            options={
                'db_table': 'partnerships_agreement_withdrawal',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('INVESTOR', 'Инвестор'), ('OPERATOR', 'Оператор')], max_length=20)),
                ('planned_capital_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit_share', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=7)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_memberships', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partnerships.investmentagreement')),
            ],
            options={
                'db_table': 'partnerships_agreement_partner',
            },
        ),
        migrations.CreateModel(
            name='AgreementContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_contributions', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='partnerships.investmentagreement')),
            ],
            options={
                'db_table': 'partnerships_agreement_contribution',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('TO_PROCUREMENT', 'В приход'), ('FROM_PROCUREMENT', 'Из прихода')], default='TO_PROCUREMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations', to='core.partner')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_allocations', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='partnerships.investmentagreement')),
            ],
            options={
                'db_table': 'partnerships_agreement_allocation',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='procurement',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='partnerships.investmentagreement'),
        ),
        migrations.RunPython(backfill_legacy_agreement_wrappers, noop_reverse),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['tenant', 'agreement'], name='partnership_tenant__9f89d2_idx'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='partnerships.procurementexpense'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_targets', to='partnerships.procurementitem'),
        ),
        migrations.AddField(
            model_name='procurementexpensetarget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='investmentagreement',
            index=models.Index(fields=['tenant', 'status'], name='partnership_tenant__5e2d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentagreement',
            index=models.Index(fields=['tenant', 'opened_at'], name='partnership_tenant__e613e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentagreement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_investment_agreement_idempotent'),
        ),
        migrations.AddIndex(
            model_name='agreementwithdrawal',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_82f1df_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementwithdrawal',
            index=models.Index(fields=['partner'], name='partnership_partner_d6ba2c_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementpartner',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_adfcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementpartner',
            index=models.Index(fields=['partner'], name='partnership_partner_5b63e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementpartner',
            constraint=models.UniqueConstraint(fields=('agreement', 'partner', 'role'), name='uq_agreement_partner_role'),
        ),
        migrations.AddIndex(
            model_name='agreementcontribution',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_823e72_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementcontribution',
            index=models.Index(fields=['partner'], name='partnership_partner_b5b91a_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_96da56_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['procurement'], name='partnership_procure_8280d0_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementallocation',
            index=models.Index(fields=['partner'], name='partnership_partner_177016_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpensetarget',
            index=models.Index(fields=['expense'], name='partnership_expense_b7bd75_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexpensetarget',
            index=models.Index(fields=['item'], name='partnership_item_id_a6073a_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementexpensetarget',
            constraint=models.UniqueConstraint(fields=('expense', 'item'), name='uq_procurement_expense_target'),
        ),
    ]
