# Generated by Django 5.1.15 on 2026-05-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0006_remove_dividendpayment_paid_from_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementterms',
            name='paid_amount',
        ),
    ]
