# Generated by Django 5.1.15 on 2026-04-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0007_alter_procurementitem_unit_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementexpense',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PAID', 'Оплачено'), ('RECEIVED', 'Оприходовано')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='procurementitem',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PAID', 'Оплачено'), ('RECEIVED', 'Оприходовано')], default='DRAFT', max_length=16),
        ),
    ]
