# Generated by Django 5.1.15 on 2026-05-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0007_remove_procurementterms_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementterms',
            name='lifecycle_state',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активный')], default='DRAFT', help_text='DRAFT — terms still being negotiated, fully mutable. ACTIVE — locked after first finance.Payment or ReceiveBatch; semantic changes require ProcurementTermsAmendment.', max_length=8),
        ),
    ]
