# Generated by Django 5.1.15 on 2026-05-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_procurementterms_lifecycle_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancewithdrawal',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='balancewithdrawal',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='balancewithdrawal',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='procurementbalance',
            name='procurement',
        ),
        migrations.RemoveField(
            model_name='procurementbalance',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='procurementbalanceexchange',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='procurementbalanceexchange',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='investmentagreement',
            name='balances',
        ),
        migrations.DeleteModel(
            name='BalanceContribution',
        ),
        migrations.DeleteModel(
            name='BalanceWithdrawal',
        ),
        migrations.DeleteModel(
            name='ProcurementBalance',
        ),
        migrations.DeleteModel(
            name='ProcurementBalanceExchange',
        ),
    ]
