# Generated by Django 5.1.15 on 2026-05-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0009_remove_balancewithdrawal_balance_and_more'),
        ('suppliers', '0003_remove_supplierpayable_supplier_payable_paid_amount_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='goods_ownership',
            field=models.CharField(choices=[('OWNED', 'Свой товар'), ('CONSIGNED', 'На реализации')], default='OWNED', help_text='E09: whether goods are owned by the business or on consignment.', max_length=12),
        ),
        migrations.AlterField(
            model_name='procurementterms',
            name='consignment_agreement',
            field=models.ForeignKey(blank=True, help_text='Only for ON_SALE type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_terms', to='suppliers.consignmentagreement'),
        ),
        migrations.AlterField(
            model_name='procurementterms',
            name='type',
            field=models.CharField(choices=[('PREPAID', 'Полная предоплата'), ('PARTIAL', 'Частичная оплата'), ('DEFERRED', 'Отсрочка'), ('INSTALLMENT', 'Рассрочка'), ('ON_SALE', 'Оплата после продажи')], max_length=16),
        ),
    ]
