# Generated by Django 5.1.15 on 2026-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0010_procurement_goods_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementterms',
            name='type',
            field=models.CharField(choices=[('PREPAID', 'Полная предоплата'), ('AT_RECEIPT', 'Оплата по получению'), ('PARTIAL', 'Частичная оплата'), ('DEFERRED', 'Отсрочка'), ('INSTALLMENT', 'Рассрочка'), ('ON_SALE', 'Оплата после продажи')], max_length=16),
        ),
    ]
