# Generated by Django 5.1.15 on 2026-05-20 (handwritten: reordered for safe backfill)

from django.db import migrations, models


def backfill_item_goods_ownership(apps, schema_editor):
    """Copy Procurement.goods_ownership to all its ProcurementItem rows."""
    Procurement = apps.get_model('partnerships', 'Procurement')
    ProcurementItem = apps.get_model('partnerships', 'ProcurementItem')
    for proc in Procurement.objects.exclude(goods_ownership=''):
        ProcurementItem.objects.filter(procurement=proc).update(
            goods_ownership=proc.goods_ownership,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0011_at_receipt_timing'),
    ]

    operations = [
        # 1. Add field first (default OWNED is safe — backfill comes next)
        migrations.AddField(
            model_name='procurementitem',
            name='goods_ownership',
            field=models.CharField(
                choices=[('OWNED', 'Свой товар'), ('CONSIGNED', 'На реализации')],
                default='OWNED',
                help_text='E09 Wave A: per-item ownership axis (OWNED or CONSIGNED).',
                max_length=12,
            ),
        ),
        # 2. Backfill from parent Procurement.goods_ownership
        migrations.RunPython(backfill_item_goods_ownership, noop_reverse),
        # 3. Remove from Procurement (replaced by @property)
        migrations.RemoveField(
            model_name='procurement',
            name='goods_ownership',
        ),
    ]
