# Generated by Django 5.1.15 on 2026-05-20 10:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0012_per_item_goods_ownership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementreceivebatchline',
            old_name='quantity',
            new_name='quantity_planned',
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='discrepancy_reason',
            field=models.CharField(choices=[('NONE', 'Без расхождения'), ('MISSING_EXPECTED_LATER', 'Не привезли, ждём'), ('DAMAGED', 'Повреждён'), ('QUALITY_REJECT', 'Отказ по качеству'), ('ACCEPT_AS_SHORTFALL', 'Закрыть с недостачей')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='procurementreceivebatchline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14),
        ),
    ]
