# Generated by Django 5.1.15 on 2026-05-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0013_discrepancy_fields_on_batch_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementreceivebatch',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procurementreceivebatch',
            name='reversed_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_batches', to='partnerships.procurementreceivebatch'),
        ),
    ]
