# Generated by Django 5.1.15 on 2026-05-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0014_reverse_receive_batch_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_type', models.CharField(choices=[('ITEMS', 'Товары'), ('EXPENSES', 'Расходы'), ('SUPPLIER', 'Поставщик')], max_length=20)),
                ('amended_at', models.DateTimeField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_amendment',
                'indexes': [models.Index(fields=['procurement', 'amended_at'], name='partnership_procure_869ee4_idx')],
            },
        ),
    ]
