# Generated by Django 5.1.15 on 2026-05-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_cashaccount_kind'),
        ('partnerships', '0015_procurement_amendment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagreement',
            name='capital_account',
            field=models.ForeignKey(blank=True, help_text='E11 capital pool cash account for this agreement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backed_agreements', to='finance.cashaccount'),
        ),
    ]
