# Generated by Django 5.1.15 on 2026-05-31 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0007_alter_cashaccount_kind'),
        ('partnerships', '0016_investmentagreement_capital_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCurrencyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pools', to='partnerships.investmentagreement')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.cashaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_agreement_currency_pool',
                'indexes': [models.Index(fields=['agreement', 'currency'], name='partnership_agreeme_8e4add_idx')],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'currency'), name='uq_agreement_currency_pool')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_currency', models.CharField(help_text='Agreement accounting currency.', max_length=3)),
                ('currency', models.CharField(help_text='Currency held by this lot (conversion target).', max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Held currency per 1 base currency at conversion.', max_digits=20)),
                ('amount_initial', models.DecimalField(decimal_places=6, max_digits=20)),
                ('amount_remaining', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_cost_initial', models.DecimalField(decimal_places=6, help_text='Base-currency amount given up to acquire this lot (cost basis).', max_digits=20)),
                ('base_cost_remaining', models.DecimalField(decimal_places=6, max_digits=20)),
                ('converted_at', models.DateTimeField()),
                ('source_ref', models.CharField(blank=True, default='', max_length=100)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_lots', to='partnerships.investmentagreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_currency_conversion_lot',
                'ordering': ['converted_at', 'id'],
                'indexes': [models.Index(fields=['agreement', 'currency', 'converted_at'], name='partnership_agreeme_4bf005_idx'), models.Index(fields=['tenant', 'currency'], name='partnership_tenant__723c53_idx')],
            },
        ),
    ]
