# Generated by Django 5.1.15 on 2026-06-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0017_agreementcurrencypool_currencyconversionlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementcontribution',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementcontribution',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dividendpayment',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
