# Generated by Django 5.1.15 on 2026-06-03 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0018_agreementcontribution_fx_rate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('CAPITAL_IN', 'Внос капитала'), ('CAPITAL_OUT', 'Вывод капитала'), ('PROFIT_ACCRUED', 'Начислена прибыль'), ('PROFIT_REVERSED', 'Сторно прибыли'), ('DIVIDEND_PAID', 'Выплачен дивиденд'), ('LOSS_INCURRED', 'Зафиксирован убыток'), ('ADVANCE_OUT', 'Капитальный аванс (выдан)'), ('ADVANCE_REPAID', 'Капитальный аванс (погашен)')], max_length=20),
        ),
        migrations.CreateModel(
            name='CapitalAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('repayment_mode', models.CharField(choices=[('LUMP', 'Единым платежом'), ('FROM_PROFIT', 'Из прибыли')], default='LUMP', max_length=16)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Не погашен'), ('PARTIAL', 'Частично погашен'), ('SETTLED', 'Погашен'), ('CANCELLED', 'Аннулирован (реверс)')], default='OUTSTANDING', max_length=16)),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_advances', to='partnerships.investmentagreement')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_advances', to='partnerships.procurementreceivebatch')),
                ('creditor', models.ForeignKey(blank=True, help_text='Partner who covered the shortfall. NULL = pool-mediated.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_advances_due', to='core.partner')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_advances_owed', to='core.partner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_capital_advance',
            },
        ),
        migrations.CreateModel(
            name='CapitalAdvanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('source', models.CharField(choices=[('CASH', 'Деньгами (пополнение/из баланса)'), ('FROM_PROFIT', 'Из нераспределённой прибыли')], max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source_ref', models.CharField(blank=True, default='', max_length=100)),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='partnerships.capitaladvance')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_capital_advance_settlement',
            },
        ),
        migrations.AddIndex(
            model_name='capitaladvance',
            index=models.Index(fields=['agreement'], name='partnership_agreeme_727182_idx'),
        ),
        migrations.AddIndex(
            model_name='capitaladvance',
            index=models.Index(fields=['batch'], name='partnership_batch_i_b57252_idx'),
        ),
        migrations.AddIndex(
            model_name='capitaladvance',
            index=models.Index(fields=['status'], name='partnership_status_b00fd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='capitaladvance',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_capital_advance_idempotent'),
        ),
        migrations.AddIndex(
            model_name='capitaladvancesettlement',
            index=models.Index(fields=['advance'], name='partnership_advance_9f63db_idx'),
        ),
        migrations.AddConstraint(
            model_name='capitaladvancesettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_advance_settlement_idempotent'),
        ),
    ]
