# Generated by Django 5.1.15 on 2026-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0019_alter_partnerledgerentry_entry_type_capitaladvance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentagreement',
            name='default_advance_repayment_mode',
            field=models.CharField(choices=[('LUMP', 'Единым платежом'), ('FROM_PROFIT', 'Из прибыли')], default='LUMP', max_length=16),
        ),
        migrations.AddField(
            model_name='investmentagreement',
            name='reconciliation_mode',
            field=models.CharField(choices=[('FACTUAL', 'Динамический пересчёт по факту'), ('AGREED', 'Держим договорные доли (разницу — в долг)')], default='FACTUAL', max_length=16),
        ),
    ]
