# Generated by Django 5.1.15 on 2026-06-04 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0020_investmentagreement_default_advance_repayment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitaladvancesettlement',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_settlements', to='partnerships.investmentagreement'),
        ),
        migrations.AddField(
            model_name='capitaladvancesettlement',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_settlements', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='capitaladvancesettlement',
            name='advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='partnerships.capitaladvance'),
        ),
        migrations.AddIndex(
            model_name='capitaladvancesettlement',
            index=models.Index(fields=['agreement', 'partner'], name='partnership_agreeme_4670e6_idx'),
        ),
    ]
