# Generated by Django 5.1.15 on 2026-06-05 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0005_lot_reversed_field'),
        ('partnerships', '0021_capitaladvancesettlement_agreement_and_more'),
        ('sales', '0003_saleline_fx_rate_date_saleline_fx_rate_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementSaleRealization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('event_type', models.CharField(choices=[('REALIZATION', 'Реализация'), ('REVERSAL', 'Сторно реализации'), ('LOSS', 'Убыток без продажи')], default='REALIZATION', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sale_proceeds_currency', models.CharField(default='UZS', max_length=3)),
                ('sale_proceeds_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('sale_fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('cost_basis_currency', models.CharField(default='UZS', max_length=3)),
                ('cost_basis_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cost_fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('sale_proceeds_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost_basis_uzs', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cost_basis_at_sale_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('capital_share', models.DecimalField(decimal_places=6, max_digits=8)),
                ('profit_share', models.DecimalField(decimal_places=6, max_digits=8)),
                ('capital_recovered_currency', models.CharField(default='UZS', max_length=3)),
                ('capital_recovered_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('profit_currency', models.CharField(default='UZS', max_length=3)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('loss_currency', models.CharField(default='UZS', max_length=3)),
                ('loss_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('fx_gain_loss_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('is_partner_liability', models.BooleanField(default=False, help_text='True when loss is assigned as partner liability, not ordinary venture loss.')),
                ('capital_recovered_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('provisional_profit_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('loss_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('source_ref', models.CharField(blank=True, default='', max_length=100)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnership_realizations', to='inventory.lot')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_sale_realizations', to='core.partner')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_realizations', to='partnerships.procurement')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_events', to='partnerships.procurementsalerealization')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnership_realizations', to='sales.saleline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_sale_realization',
                'indexes': [models.Index(fields=['procurement', 'partner'], name='psr_proc_partner_idx'), models.Index(fields=['sale_line'], name='psr_line_idx'), models.Index(fields=['tenant', 'event_type'], name='psr_event_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_type', 'REALIZATION')), fields=('sale_line', 'partner', 'event_type'), name='uq_sale_realization_line_partner')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementVentureSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('settlement_type', models.CharField(choices=[('CONSTRUCTIVE', 'Конструктивная ликвидация'), ('FINAL', 'Финальная ликвидация')], max_length=16)),
                ('settled_at', models.DateTimeField()),
                ('inventory_value_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('reserve_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('partner_positions', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venture_settlements', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_procurement_venture_settlement',
                'indexes': [models.Index(fields=['procurement', 'settled_at'], name='pvs_proc_idx'), models.Index(fields=['tenant', 'settlement_type'], name='pvs_type_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_procurement_venture_settlement_idempotent')],
            },
        ),
    ]
