# Generated by Django 5.1.15 on 2026-06-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_journalentry_operation_type'),
        ('partnerships', '0022_procurementsalerealization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='paid_from_account',
            field=models.ForeignKey(blank=True, help_text='E16: operating cash source when returning recovered proceeds directly.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreement_capital_withdrawals', to='finance.cashaccount'),
        ),
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='procurement',
            field=models.ForeignKey(blank=True, help_text='E16: procurement-venture this capital return is attributed to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_withdrawals', to='partnerships.procurement'),
        ),
    ]
