# Generated by Django 5.1.15 on 2026-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0024_repair_procurement_sale_realization_currency_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentagreement',
            name='default_advance_repayment_mode',
        ),
    ]
