# Generated by Django 5.1.15 on 2026-06-13 18:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0010_alter_journalentry_operation_type'),
        ('partnerships', '0025_remove_investmentagreement_default_advance_repayment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPartnerVentureDebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('fx_rate_source', models.CharField(blank=True, default='', max_length=16)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('repaid_liability_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('repaid_capital_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('repaid_dividend_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('paid_to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venture_debt_repayments', to='finance.cashaccount')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venture_debt_repayments', to='core.partner')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_repayments', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_partner_venture_debt_repayment',
                'indexes': [models.Index(fields=['procurement', 'partner'], name='pvdr_proc_partner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_partner_venture_debt_repayment_idempotent')],
            },
        ),
    ]
