# Generated by Django 5.1.15 on 2026-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0026_procurementpartnerventuredebtrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementallocation',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система'), ('PROFIT_REINVEST', 'Реинвестирование прибыли')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='agreementcontribution',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система'), ('PROFIT_REINVEST', 'Реинвестирование прибыли')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='agreementevent',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система'), ('PROFIT_REINVEST', 'Реинвестирование прибыли')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='agreementwithdrawal',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система'), ('PROFIT_REINVEST', 'Реинвестирование прибыли')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='capitalcommitment',
            name='source',
            field=models.CharField(choices=[('BUSINESS_RECORDED', 'Зафиксировано бизнесом'), ('INVESTOR_SUBMITTED', 'Отправлено инвестором'), ('SYSTEM', 'Система'), ('PROFIT_REINVEST', 'Реинвестирование прибыли')], default='BUSINESS_RECORDED', max_length=24),
        ),
        migrations.AlterField(
            model_name='partnerledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('CAPITAL_IN', 'Внос капитала'), ('CAPITAL_OUT', 'Вывод капитала'), ('PROFIT_ACCRUED', 'Начислена прибыль'), ('PROFIT_REVERSED', 'Сторно прибыли'), ('DIVIDEND_PAID', 'Выплачен дивиденд'), ('PROFIT_TO_CAPITAL', 'Прибыль → капитал'), ('LOSS_INCURRED', 'Зафиксирован убыток'), ('ADVANCE_OUT', 'Капитальный аванс (выдан)'), ('ADVANCE_REPAID', 'Капитальный аванс (погашен)')], max_length=20),
        ),
    ]
