# Generated by Django 5.1.15 on 2026-06-16 07:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0027_alter_agreementallocation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPositionReadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('deployed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('paid_in', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('owed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('withdrawable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('deployed_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('capital_recovered_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('provisional_profit_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('loss_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('partner_liability_loss_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('capital_returned_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('dividends_paid_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('profit_to_capital_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('remaining_inventory_capital_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('liability_capital_recovered_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('capital_return_available_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('provisional_profit_available_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('negative_position_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('negative_liability_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('negative_capital_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('negative_dividend_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('debt_repaid_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('computed_at', models.DateTimeField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_position_rows', to='partnerships.investmentagreement')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_read_model_rows', to='core.partner')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_position_rows', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_partner_position_read_model',
                'indexes': [models.Index(fields=['tenant', 'agreement', 'partner', 'currency'], name='pprm_agreement_idx'), models.Index(fields=['tenant', 'procurement', 'partner', 'currency'], name='pprm_procurement_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'agreement', 'procurement', 'partner', 'currency'), name='uq_partner_position_read_model', nulls_distinct=False)],
            },
        ),
    ]
