# Generated by Django 5.1.15 on 2026-06-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0011_alter_journalentry_operation_type'),
        ('partnerships', '0028_partnerpositionreadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerJournalLineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pocket', models.CharField(choices=[('CAPITAL', 'Capital'), ('PROCEEDS', 'Proceeds'), ('DISTRIBUTION', 'Distribution')], max_length=16)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_line_tags', to='partnerships.investmentagreement')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_tags', to='finance.journalline')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_line_tags', to='core.partner')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_line_tags', to='partnerships.procurement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_partner_journal_line_tag',
                'indexes': [models.Index(fields=['tenant', 'agreement', 'partner', 'pocket'], name='pjlt_agreement_idx'), models.Index(fields=['tenant', 'procurement', 'partner', 'pocket'], name='pjlt_procurement_idx'), models.Index(fields=['journal_line'], name='pjlt_line_idx')],
                'constraints': [models.UniqueConstraint(fields=('journal_line', 'partner', 'agreement', 'procurement', 'pocket'), name='uq_partner_journal_line_tag', nulls_distinct=False)],
            },
        ),
    ]
