# Generated by Django 5.1.15 on 2026-06-16 08:42

from django.db import migrations, models


def backfill_return_kind(apps, schema_editor):
    AgreementWithdrawal = apps.get_model('partnerships', 'AgreementWithdrawal')
    CashEntry = apps.get_model('finance', 'CashEntry')

    withdrawals = (
        AgreementWithdrawal.objects
        .select_related('agreement')
        .only('id', 'agreement__capital_account_id')
        .iterator()
    )
    for withdrawal in withdrawals:
        pool_account_id = withdrawal.agreement.capital_account_id
        is_pool_return = bool(pool_account_id) and CashEntry.objects.filter(
            source_ref_type='agreement_withdrawal',
            source_ref_id=withdrawal.id,
            account_id=pool_account_id,
            direction='OUT',
        ).exists()
        AgreementWithdrawal.objects.filter(pk=withdrawal.id).update(
            return_kind='FROM_POOL' if is_pool_return else 'FROM_PROCEEDS',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0029_partnerjournallinetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementwithdrawal',
            name='return_kind',
            field=models.CharField(choices=[('FROM_POOL', 'From pool'), ('FROM_PROCEEDS', 'From proceeds')], default='FROM_POOL', help_text='E18: explicit capital return classification.', max_length=16),
        ),
        migrations.RunPython(backfill_return_kind, migrations.RunPython.noop),
    ]
