# Generated by Django 5.1.15 on 2026-06-16 09:59

from django.db import migrations, models


def backfill_flow(apps, schema_editor):
    PartnerJournalLineTag = apps.get_model('partnerships', 'PartnerJournalLineTag')

    rows = (
        PartnerJournalLineTag.objects
        .select_related(
            'agreement',
            'agreement__capital_account',
            'agreement__capital_account__linked_account',
            'journal_line',
            'journal_line__account',
            'journal_line__journal_entry',
        )
        .iterator()
    )
    for tag in rows:
        line = tag.journal_line
        entry = line.journal_entry
        account_code = line.account.code
        operation_type = entry.operation_type
        flow = 'CONTRIBUTION'

        if operation_type == 'capital_contribution':
            flow = 'CONTRIBUTION'
        elif operation_type == 'profit_distrib':
            flow = 'DIVIDEND'
        elif operation_type == 'advance_settle':
            flow = 'PROFIT_TO_CAPITAL'
        elif operation_type == 'venture_debt_repay':
            if account_code == '5100':
                flow = 'DEBT_REPAID_LIABILITY'
            elif account_code == '3200':
                flow = 'DEBT_REPAID_DIVIDEND'
            else:
                flow = 'DEBT_REPAID_CAPITAL'
        elif operation_type == 'capital_return':
            pool_code = None
            if (
                tag.agreement.capital_account_id
                and tag.agreement.capital_account.linked_account_id
            ):
                pool_code = tag.agreement.capital_account.linked_account.code
            if tag.procurement_id is None:
                flow = 'POOL_RETURN'
            elif pool_code and account_code == pool_code and line.debit:
                flow = 'OVERPAYMENT_REFUND'
            else:
                flow = 'CAPITAL_RETURN'

        PartnerJournalLineTag.objects.filter(pk=tag.pk).update(flow=flow)


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0030_agreementwithdrawal_return_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerjournallinetag',
            name='flow',
            field=models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('POOL_RETURN', 'Pool return'), ('PROCEEDS_RETURN', 'Proceeds return'), ('DIVIDEND', 'Dividend'), ('PROFIT_TO_CAPITAL', 'Profit to capital'), ('CAPITAL_RETURN', 'Capital return'), ('OVERPAYMENT_REFUND', 'Overpayment refund'), ('DEBT_REPAID_LIABILITY', 'Debt repaid liability'), ('DEBT_REPAID_CAPITAL', 'Debt repaid capital'), ('DEBT_REPAID_DIVIDEND', 'Debt repaid dividend')], default='CONTRIBUTION', max_length=32),
        ),
        migrations.RunPython(backfill_flow, migrations.RunPython.noop),
    ]
