# Generated by Django 5.1.15 on 2026-06-23 12:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0033_agreementtermsversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPositionReadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('paid_in', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('deployed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('provisional_profit_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('capital_return_available_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('profit_available_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('manager_fee_accrued_uzs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('computed_at', models.DateTimeField()),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_row', to='partnerships.investmentfund')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_fund_position_read_model',
            },
        ),
    ]
