# Generated by Django 5.1.15 on 2026-06-23 12:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def _agreement_snapshot(agreement, partners):
    return {
        'legacy_migrated': True,
        'legal_mode': agreement.legal_mode,
        'reconciliation_mode': agreement.reconciliation_mode,
        'loss_rule': agreement.loss_rule,
        'mudaraba_ratio': str(agreement.mudaraba_ratio),
        'planned_budget': str(agreement.planned_budget),
        'currency': str(agreement.currency or 'UZS').upper(),
        'parties': [
            {
                'partner_id': row.partner_id,
                'role': row.role,
                'planned_capital_share': str(row.planned_capital_share),
                'profit_share': str(row.profit_share),
            }
            for row in partners
        ],
    }


def _fund_snapshot(fund, members, terms):
    return {
        'legacy_migrated': True,
        'name': fund.name,
        'currency': str(fund.currency or 'UZS').upper(),
        'target_amount': str(fund.target_amount) if fund.target_amount is not None else None,
        'manager_partner_id': fund.manager_partner_id,
        'manager_profit_share': str(terms.manager_profit_share),
        'members': sorted(row.partner_id for row in members),
        'waterfall': ['capital_return', 'net_profit', 'manager_fee'],
    }


def populate_legacy_terms(apps, schema_editor):
    Agreement = apps.get_model('partnerships', 'InvestmentAgreement')
    AgreementPartner = apps.get_model('partnerships', 'AgreementPartner')
    AgreementTerms = apps.get_model('partnerships', 'AgreementTermsVersion')
    Fund = apps.get_model('partnerships', 'InvestmentFund')
    FundMember = apps.get_model('partnerships', 'FundMember')
    FundTerms = apps.get_model('partnerships', 'FundTermsVersion')
    PayoutPolicy = apps.get_model('partnerships', 'PayoutPolicy')

    for agreement in Agreement.objects.filter(current_terms__isnull=True).iterator():
        term = AgreementTerms.objects.create(
            tenant_id=agreement.tenant_id,
            agreement_id=agreement.pk,
            version=1,
            effective_at=agreement.opened_at,
            terms_snapshot=_agreement_snapshot(
                agreement,
                AgreementPartner.objects.filter(agreement_id=agreement.pk).order_by('role', 'partner_id'),
            ),
            notes='E20 conservative migration of pre-versioned agreement terms.',
        )
        PayoutPolicy.objects.create(tenant_id=agreement.tenant_id, agreement_terms_id=term.pk)
        agreement.current_terms_id = term.pk
        agreement.save(update_fields=['current_terms'])

    for term in AgreementTerms.objects.filter(terms_snapshot={}).iterator():
        agreement = Agreement.objects.get(pk=term.agreement_id)
        term.terms_snapshot = _agreement_snapshot(
            agreement,
            AgreementPartner.objects.filter(agreement_id=agreement.pk).order_by('role', 'partner_id'),
        )
        term.save(update_fields=['terms_snapshot'])
        PayoutPolicy.objects.get_or_create(
            tenant_id=term.tenant_id,
            agreement_terms_id=term.pk,
        )

    for term in FundTerms.objects.filter(terms_snapshot={}).iterator():
        fund = Fund.objects.get(pk=term.fund_id)
        term.terms_snapshot = _fund_snapshot(
            fund,
            FundMember.objects.filter(fund_id=fund.pk),
            term,
        )
        term.save(update_fields=['terms_snapshot'])
        PayoutPolicy.objects.get_or_create(
            tenant_id=term.tenant_id,
            fund_terms_id=term.pk,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0034_fundpositionreadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementtermsversion',
            name='terms_snapshot',
            field=models.JSONField(default=dict, help_text='Immutable economic parties and rule inputs captured when this version became effective.'),
        ),
        migrations.AddField(
            model_name='fundtermsversion',
            name='terms_snapshot',
            field=models.JSONField(default=dict, help_text='Immutable fund parties and waterfall inputs captured when this version became effective.'),
        ),
        migrations.AddField(
            model_name='payoutobligation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='payoutpolicy',
            name='last_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PayoutSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('settled_at', models.DateTimeField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('capital_withdrawal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_settlement', to='partnerships.agreementwithdrawal')),
                ('dividend_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_settlement', to='partnerships.dividendpayment')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='partnerships.payoutobligation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'partnerships_payout_settlement',
                'ordering': ['settled_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('capital_withdrawal__isnull', True), ('dividend_payment__isnull', False)), models.Q(('capital_withdrawal__isnull', False), ('dividend_payment__isnull', True)), models.Q(('capital_withdrawal__isnull', True), ('dividend_payment__isnull', True)), _connector='OR'), name='payout_settlement_at_most_one_direct_payment')],
            },
        ),
        migrations.RunPython(populate_legacy_terms, migrations.RunPython.noop),
    ]
