# Generated by Django 5.1.15 on 2026-06-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partnerships', '0035_e20_terms_snapshot_payout_settlement'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payoutobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('agreement__isnull', False), ('status__in', ['PENDING', 'RECORDED', 'DISPUTED'])), fields=('agreement', 'recipient', 'procurement', 'kind'), name='uq_agreement_open_payout_obligation', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='payoutobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('fund__isnull', False), ('status__in', ['PENDING', 'RECORDED', 'DISPUTED'])), fields=('fund', 'recipient', 'kind'), name='uq_fund_open_payout_obligation'),
        ),
    ]
