# Generated by Django 5.1.15 on 2026-06-25 07:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0012_alter_cashaccount_kind_alter_payment_target_type_and_more'),
        ('partnerships', '0036_e20_active_obligation_uniqueness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_fund_application',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FundMemberExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(choices=[('MEMBER_EXIT', 'Выход участника'), ('MANAGER_REMOVE', 'Удаление управляющим')], max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('refunded_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('client_request_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'partnerships_fund_member_exit',
                'ordering': ['-refunded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fundmember',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='fundmember',
            name='confirmed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='fundmember',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('EXITED', 'Вышел до размещения'), ('REMOVED', 'Удалён до размещения')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='investmentfund',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='investmentfund',
            name='min_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='investmentfund',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE_INVITE', 'Закрытый по приглашению'), ('PUBLIC_LISTING', 'Публичная заявка')], default='PRIVATE_INVITE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='investmentfund',
            constraint=models.UniqueConstraint(condition=models.Q(('invite_token__isnull', False)), fields=('invite_token',), name='uq_investment_fund_invite_token'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_applications_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='partnerships.investmentfund'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_applications', to='core.partner'),
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddField(
            model_name='fundmember',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='partnerships.fundapplication'),
        ),
        migrations.AddField(
            model_name='fundmemberexit',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_exits', to='partnerships.investmentfund'),
        ),
        migrations.AddField(
            model_name='fundmemberexit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exits', to='partnerships.fundmember'),
        ),
        migrations.AddField(
            model_name='fundmemberexit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business'),
        ),
        migrations.AddConstraint(
            model_name='fundapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('fund', 'partner'), name='uq_fund_pending_application'),
        ),
        migrations.AddConstraint(
            model_name='fundmemberexit',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('tenant', 'client_request_id'), name='uq_fund_member_exit_idempotent'),
        ),
    ]
