# Generated by Django 5.1.15 on 2026-06-25 07:59

import apps.core.models as core_models
from django.db import migrations, models


def backfill_invite_tokens(apps, schema_editor):
    InvestmentFund = apps.get_model('partnerships', 'InvestmentFund')
    existing = set(
        InvestmentFund.objects
        .exclude(invite_token__isnull=True)
        .exclude(invite_token='')
        .values_list('invite_token', flat=True)
    )
    for fund in InvestmentFund.objects.filter(invite_token__isnull=True).iterator():
        token = core_models.generate_invite_token()
        while token in existing:
            token = core_models.generate_invite_token()
        existing.add(token)
        fund.invite_token = token
        fund.save(update_fields=['invite_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0037_fundapplication_fundmemberexit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentfund',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, default=core_models.generate_invite_token, max_length=96, null=True),
        ),
        migrations.RunPython(backfill_invite_tokens, migrations.RunPython.noop),
    ]
