# Generated by Django 5.1.15 on 2026-07-04 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_investment_profiles(apps, schema_editor):
    InvestmentProfile = apps.get_model('core', 'InvestmentProfile')
    InvestmentFund = apps.get_model('partnerships', 'InvestmentFund')
    FundMember = apps.get_model('partnerships', 'FundMember')
    FundApplication = apps.get_model('partnerships', 'FundApplication')

    def profile_for_partner(partner):
        user_id = getattr(partner, 'user_id', None)
        if not user_id:
            return None
        profile, _ = InvestmentProfile.objects.get_or_create(
            user_id=user_id,
            defaults={
                'display_name': partner.display_name or f'Investor #{user_id}',
                'is_active': True,
            },
        )
        return profile

    for fund in InvestmentFund.objects.select_related('manager_partner').filter(manager_profile__isnull=True):
        if fund.manager_partner_id:
            profile = profile_for_partner(fund.manager_partner)
            if profile is not None:
                fund.manager_profile_id = profile.pk
                fund.save(update_fields=['manager_profile'])

    for member in FundMember.objects.select_related('partner').filter(profile__isnull=True, partner__isnull=False):
        profile = profile_for_partner(member.partner)
        if profile is not None:
            member.profile_id = profile.pk
            member.save(update_fields=['profile'])

    for application in FundApplication.objects.select_related('partner').filter(profile__isnull=True, partner__isnull=False):
        profile = profile_for_partner(application.partner)
        if profile is not None:
            application.profile_id = profile.pk
            application.save(update_fields=['profile'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investmentprofile'),
        ('finance', '0012_alter_cashaccount_kind_alter_payment_target_type_and_more'),
        ('partnerships', '0038_alter_investmentfund_invite_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_applications', to='core.investmentprofile'),
        ),
        migrations.AddField(
            model_name='fundmember',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_memberships', to='core.investmentprofile'),
        ),
        migrations.AddField(
            model_name='investmentfund',
            name='manager_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_investment_funds', to='core.investmentprofile'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_applications', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='fundapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundapplication_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundcontribution',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundcontribution_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundmember',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_memberships', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='fundmember',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundmember_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundmemberexit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundmemberexit_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundmemberpositionreadmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundmemberpositionreadmodel_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundpositionreadmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundpositionreadmodel_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='fundtermsversion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_fundtermsversion_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='investmentfund',
            name='capital_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backed_investment_funds', to='finance.cashaccount'),
        ),
        migrations.AlterField(
            model_name='investmentfund',
            name='holder_partner',
            field=models.OneToOneField(blank=True, help_text='Synthetic investor partner representing this fund in external agreements.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_fund_holder', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='investmentfund',
            name='manager_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_investment_funds', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='investmentfund',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_investmentfund_set', to='core.business'),
        ),
        migrations.AlterField(
            model_name='payoutpolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerships_payoutpolicy_set', to='core.business'),
        ),
        migrations.AddIndex(
            model_name='investmentfund',
            index=models.Index(fields=['manager_profile', 'status'], name='partnership_manager_198ede_idx'),
        ),
        migrations.RunPython(backfill_investment_profiles, noop_reverse),
        migrations.AddConstraint(
            model_name='fundapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False), ('status', 'PENDING')), fields=('fund', 'profile'), name='uq_fund_pending_application_profile'),
        ),
        migrations.AddConstraint(
            model_name='fundmember',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('fund', 'profile'), name='uq_fund_member_profile'),
        ),
    ]
