# Generated by Codex on 2026-07-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investmentprofile'),
        ('partnerships', '0039_fundapplication_profile_fundmember_profile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payoutobligation',
            name='uq_fund_open_payout_obligation',
        ),
        migrations.AddField(
            model_name='disputecase',
            name='raised_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to='core.investmentprofile'),
        ),
        migrations.AddField(
            model_name='payoutobligation',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_obligations', to='core.investmentprofile'),
        ),
        migrations.AlterField(
            model_name='disputecase',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='payoutobligation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_obligations', to='core.partner'),
        ),
        migrations.AddConstraint(
            model_name='fundcontribution',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('fund', 'client_request_id'), name='uq_fund_contribution_fund_request'),
        ),
        migrations.AddConstraint(
            model_name='payoutobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('fund__isnull', False), ('recipient__isnull', False), ('status__in', ['PENDING', 'RECORDED', 'DISPUTED'])), fields=('fund', 'recipient', 'kind'), name='uq_fund_open_payout_obligation'),
        ),
        migrations.AddConstraint(
            model_name='payoutobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('fund__isnull', False), ('recipient_profile__isnull', False), ('status__in', ['PENDING', 'RECORDED', 'DISPUTED'])), fields=('fund', 'recipient_profile', 'kind'), name='uq_fund_open_payout_obligation_profile'),
        ),
    ]
