# Generated by Django 5.1.15 on 2026-04-18 09:03

import apps.core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investors_investor',
            },
        ),
        migrations.CreateModel(
            name='InvestorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contract_type', models.CharField(choices=[('MUDARABA', 'Мудараба'), ('MUSHARAKA', 'Мушарака')], max_length=20)),
                ('default_profit_ratio', models.DecimalField(decimal_places=4, help_text='Default investor profit share for this contract.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('active', 'Активный'), ('closed', 'Закрыт')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('final_settlement', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount owed to investor at closure.', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='investors.investor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'investors_contract',
            },
            bases=(apps.core.models.ImmutableMixin, models.Model),
        ),
    ]
