# Generated by Django 5.1.15 on 2026-04-18 09:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'customers_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский перевод')], max_length=10)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'customers_payment',
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('balances', models.JSONField(default=dict, help_text='Map<currency, decimal_string>. Positive = owes us.')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'customers_receivable',
            },
        ),
        migrations.CreateModel(
            name='ReceivableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('entry_type', models.CharField(choices=[('DEBT_ACCRUED', 'Долг начислен'), ('REPAYMENT', 'Погашение'), ('ADJUSTMENT', 'Корректировка'), ('WRITE_OFF', 'Списание')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, default='', help_text='E.g. "sale:42", "customer_payment:7"', max_length=100)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='customers.receivable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.business')),
            ],
            options={
                'db_table': 'customers_receivable_entry',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'name'], name='customers_c_tenant__5b0286_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpayment',
            index=models.Index(fields=['tenant', 'date'], name='customers_p_tenant__70fd00_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableentry',
            index=models.Index(fields=['receivable', 'entry_type'], name='customers_r_receiva_5db656_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableentry',
            index=models.Index(fields=['tenant', 'date'], name='customers_r_tenant__0ff6bd_idx'),
        ),
    ]
