# Generated by Django 5.1.15 on 2026-05-18 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payment_source_type'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salepayment',
            name='account_id',
        ),
        migrations.AddField(
            model_name='salepayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.cashaccount'),
        ),
    ]
