# Generated by Django 5.1.15 on 2026-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_salepayment_account_id_salepayment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleline',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='fx_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='fx_rate_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
