# Generated by Django 5.1.15 on 2026-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleline_fx_rate_date_saleline_fx_rate_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
